export type ConfTier = "HIGH" | "MED" | "COND";

export const SEASON_RECORD = {
  wins: 187,
  losses: 142,
  pct: 56.8,
  streak: "W4",
};

export const TICKER_ITEMS = [
  {
    id: "t1",
    away: "BOS",
    home: "NYK",
    awayScore: null,
    homeScore: null,
    status: "7:30 PM",
    isLive: false,
    isFinal: false,
  },
  {
    id: "t2",
    away: "LAL",
    home: "DEN",
    awayScore: 94,
    homeScore: 107,
    status: "Q3 4:22",
    isLive: true,
    isFinal: false,
  },
  {
    id: "t3",
    away: "GSW",
    home: "MIN",
    awayScore: null,
    homeScore: null,
    status: "10:00 PM",
    isLive: false,
    isFinal: false,
  },
  {
    id: "t4",
    away: "MIL",
    home: "PHX",
    awayScore: 118,
    homeScore: 103,
    status: "FINAL",
    isLive: false,
    isFinal: true,
  },
  {
    id: "t5",
    away: "DAL",
    home: "CLE",
    awayScore: null,
    homeScore: null,
    status: "7:00 PM",
    isLive: false,
    isFinal: false,
  },
  {
    id: "t6",
    away: "MIA",
    home: "TOR",
    awayScore: 87,
    homeScore: 91,
    status: "Q2 1:45",
    isLive: true,
    isFinal: false,
  },
  {
    id: "t7",
    away: "ATL",
    home: "ORL",
    awayScore: 101,
    homeScore: 98,
    status: "FINAL",
    isLive: false,
    isFinal: true,
  },
  {
    id: "t8",
    away: "PHI",
    home: "BKN",
    awayScore: null,
    homeScore: null,
    status: "6:30 PM",
    isLive: false,
    isFinal: false,
  },
];

export const GAMES = [
  {
    id: "g1",
    away: {
      abbr: "BOS",
      name: "Boston Celtics",
      record: "52-19",
      spread: "-4.5",
      ml: "-195",
    },
    home: {
      abbr: "NYK",
      name: "New York Knicks",
      record: "44-27",
      spread: "+4.5",
      ml: "+165",
    },
    tipoff: "7:30 PM ET",
    network: "ESPN",
    status: "upcoming",
    isLive: false,
    isFinal: false,
    awayScore: null,
    homeScore: null,
    quarter: null,
    timeRemaining: null,
    totalLine: "o/u 222.5",
    confidence: "HIGH" as ConfTier,
    pick: "NYK",
    pickReason: "Home court + Brunson L5 surge",
    pickProb: 63,
    winProbData: [
      { t: 0, bos: 55, nyk: 45 },
      { t: 6, bos: 52, nyk: 48 },
      { t: 12, bos: 48, nyk: 52 },
      { t: 18, bos: 44, nyk: 56 },
      { t: 24, bos: 42, nyk: 58 },
      { t: 30, bos: 45, nyk: 55 },
      { t: 36, bos: 41, nyk: 59 },
      { t: 42, bos: 38, nyk: 62 },
    ],
    keyStats: [
      { label: "Brunson H2H Avg", value: "28.4 pts" },
      { label: "BOS Away ATS", value: "18-24" },
      { label: "NYK Home Pace", value: "101.2" },
      { label: "Spread Trend", value: "NYK +4.5 (6-2 L8)" },
    ],
  },
  {
    id: "g2",
    away: {
      abbr: "LAL",
      name: "Los Angeles Lakers",
      record: "37-34",
      spread: "+7.5",
      ml: "+265",
    },
    home: {
      abbr: "DEN",
      name: "Denver Nuggets",
      record: "49-22",
      spread: "-7.5",
      ml: "-320",
    },
    tipoff: "LIVE · Q3 4:22",
    network: "TNT",
    status: "live",
    isLive: true,
    isFinal: false,
    awayScore: 94,
    homeScore: 107,
    quarter: 3,
    timeRemaining: "4:22",
    totalLine: "o/u 228.0",
    confidence: "HIGH" as ConfTier,
    pick: "DEN",
    pickReason: "Jokic dominance / Lakers no answer in post",
    pickProb: 78,
    winProbData: [
      { t: 0, den: 68, lal: 32 },
      { t: 6, den: 71, lal: 29 },
      { t: 12, den: 74, lal: 26 },
      { t: 18, den: 72, lal: 28 },
      { t: 24, den: 76, lal: 24 },
      { t: 30, den: 79, lal: 21 },
      { t: 36, den: 77, lal: 23 },
      { t: 42, den: 80, lal: 20 },
    ],
    keyStats: [
      { label: "Jokic pts/game vs LAL", value: "32.1" },
      { label: "DEN Home Record", value: "29-8" },
      { label: "LAL Away ATS", value: "14-23" },
      { label: "Live Win Prob", value: "DEN 78%" },
    ],
  },
  {
    id: "g3",
    away: {
      abbr: "GSW",
      name: "Golden State Warriors",
      record: "36-35",
      spread: "+6.0",
      ml: "+225",
    },
    home: {
      abbr: "MIN",
      name: "Minnesota Timberwolves",
      record: "47-24",
      spread: "-6.0",
      ml: "-275",
    },
    tipoff: "10:00 PM ET",
    network: "TNT",
    status: "upcoming",
    isLive: false,
    isFinal: false,
    awayScore: null,
    homeScore: null,
    quarter: null,
    timeRemaining: null,
    totalLine: "o/u 217.5",
    confidence: "HIGH" as ConfTier,
    pick: "MIN",
    pickReason: "Edwards 34.2 avg at home L10 / GSW defense 28th",
    pickProb: 72,
    winProbData: [
      { t: 0, min: 62, gsw: 38 },
      { t: 6, min: 65, gsw: 35 },
      { t: 12, min: 68, gsw: 32 },
      { t: 18, min: 64, gsw: 36 },
      { t: 24, min: 70, gsw: 30 },
      { t: 30, min: 67, gsw: 33 },
      { t: 36, min: 72, gsw: 28 },
      { t: 42, min: 74, gsw: 26 },
    ],
    keyStats: [
      { label: "Edwards Home L10 Avg", value: "34.2 pts" },
      { label: "GSW Def Rating", value: "28th (115.4)" },
      { label: "MIN Home Record", value: "27-10" },
      { label: "Series History", value: "MIN 3-1" },
    ],
  },
  {
    id: "g4",
    away: {
      abbr: "MIL",
      name: "Milwaukee Bucks",
      record: "43-28",
      spread: "-3.0",
      ml: "-160",
    },
    home: {
      abbr: "PHX",
      name: "Phoenix Suns",
      record: "31-40",
      spread: "+3.0",
      ml: "+140",
    },
    tipoff: "9:00 PM ET",
    network: "NBA TV",
    status: "upcoming",
    isLive: false,
    isFinal: false,
    awayScore: null,
    homeScore: null,
    quarter: null,
    timeRemaining: null,
    totalLine: "o/u 225.5",
    confidence: "MED" as ConfTier,
    pick: "MIL",
    pickReason: "Playoff positioning + PHX without Beal",
    pickProb: 57,
    winProbData: [
      { t: 0, mil: 55, phx: 45 },
      { t: 6, mil: 57, phx: 43 },
      { t: 12, mil: 54, phx: 46 },
      { t: 18, mil: 58, phx: 42 },
      { t: 24, mil: 55, phx: 45 },
      { t: 30, mil: 60, phx: 40 },
      { t: 36, mil: 57, phx: 43 },
      { t: 42, mil: 61, phx: 39 },
    ],
    keyStats: [
      { label: "Giannis vs PHX Avg", value: "31.4 pts" },
      { label: "PHX Without Beal", value: "8-14" },
      { label: "MIL Away ATS", value: "22-18" },
      { label: "Total Trend", value: "Under 6-2 L8" },
    ],
  },
  {
    id: "g5",
    away: {
      abbr: "DAL",
      name: "Dallas Mavericks",
      record: "38-33",
      spread: "+8.5",
      ml: "+300",
    },
    home: {
      abbr: "CLE",
      name: "Cleveland Cavaliers",
      record: "54-17",
      spread: "-8.5",
      ml: "-370",
    },
    tipoff: "7:00 PM ET",
    network: "ESPN",
    status: "upcoming",
    isLive: false,
    isFinal: false,
    awayScore: null,
    homeScore: null,
    quarter: null,
    timeRemaining: null,
    totalLine: "o/u 220.0",
    confidence: "COND" as ConfTier,
    pick: "CLE",
    pickReason: "CLE 28-5 at home. DAL depth question marks",
    pickProb: 52,
    winProbData: [
      { t: 0, cle: 58, dal: 42 },
      { t: 6, cle: 54, dal: 46 },
      { t: 12, cle: 60, dal: 40 },
      { t: 18, cle: 57, dal: 43 },
      { t: 24, cle: 62, dal: 38 },
      { t: 30, cle: 59, dal: 41 },
      { t: 36, cle: 63, dal: 37 },
      { t: 42, cle: 65, dal: 35 },
    ],
    keyStats: [
      { label: "CLE Home Record", value: "28-5" },
      { label: "DAL Away Record", value: "14-20" },
      { label: "Luka vs CLE Avg", value: "36.2 pts" },
      { label: "Line Movement", value: "CLE -7 → -8.5" },
    ],
  },
  {
    id: "g6",
    away: {
      abbr: "MIA",
      name: "Miami Heat",
      record: "36-35",
      spread: "+1.5",
      ml: "+110",
    },
    home: {
      abbr: "TOR",
      name: "Toronto Raptors",
      record: "22-49",
      spread: "-1.5",
      ml: "-130",
    },
    tipoff: "LIVE · Q2 1:45",
    network: "Bally",
    status: "live",
    isLive: true,
    isFinal: false,
    awayScore: 87,
    homeScore: 91,
    quarter: 2,
    timeRemaining: "1:45",
    totalLine: "o/u 212.5",
    confidence: "MED" as ConfTier,
    pick: "MIA",
    pickReason: "Playoff urgency + Butler return",
    pickProb: 61,
    winProbData: [
      { t: 0, mia: 55, tor: 45 },
      { t: 6, mia: 52, tor: 48 },
      { t: 12, mia: 58, tor: 42 },
      { t: 18, mia: 50, tor: 50 },
      { t: 24, mia: 55, tor: 45 },
      { t: 30, mia: 60, tor: 40 },
      { t: 36, mia: 57, tor: 43 },
      { t: 42, mia: 62, tor: 38 },
    ],
    keyStats: [
      { label: "Butler Return Impact", value: "+8.4 net rtg" },
      { label: "MIA L5", value: "4-1" },
      { label: "TOR Home L10", value: "3-7" },
      { label: "Live Win Prob", value: "MIA 61%" },
    ],
  },
];

export const PLAYERS = [
  {
    id: "sga",
    name: "Shai Gilgeous-Alexander",
    abbr: "SGA",
    team: "Oklahoma City Thunder",
    teamAbbr: "OKC",
    position: "PG",
    age: 25,
    tier: "S" as const,
    pts: 31.4,
    reb: 5.5,
    ast: 6.2,
    stl: 2.0,
    blk: 0.9,
    fg: 53.5,
    ft: 87.2,
    tpm: 2.3,
    imageInitials: "SG",
    identitySentence:
      "The most elegant scorer of his generation — creates advantage from stillness.",
    radarStats: { pts: 95, reb: 55, ast: 70, def: 88, eff: 92 },
    trending: "up",
    props: [
      {
        label: "Points",
        line: 30.5,
        recommendation: "OVER",
        prob: 67,
        conf: "HIGH" as ConfTier,
      },
      {
        label: "Assists",
        line: 5.5,
        recommendation: "OVER",
        prob: 59,
        conf: "MED" as ConfTier,
      },
      {
        label: "3-Pointers",
        line: 2.5,
        recommendation: "UNDER",
        prob: 54,
        conf: "COND" as ConfTier,
      },
    ],
    scoutNote:
      "SGA's isolation efficiency (1.14 PPP) is top-3 in the league. At the free throw line, he's nearly automatic. Thunder's playoff ceiling rises and falls with how he performs in Q4.",
  },
  {
    id: "jokic",
    name: "Nikola Jokic",
    abbr: "NJ",
    team: "Denver Nuggets",
    teamAbbr: "DEN",
    position: "C",
    age: 29,
    tier: "S" as const,
    pts: 26.4,
    reb: 12.4,
    ast: 9.0,
    stl: 1.4,
    blk: 0.9,
    fg: 58.3,
    ft: 82.1,
    tpm: 0.8,
    imageInitials: "NJ",
    identitySentence:
      "Basketball's greatest mind — sees the game three passes ahead of everyone else.",
    radarStats: { pts: 88, reb: 97, ast: 94, def: 65, eff: 99 },
    trending: "up",
    props: [
      {
        label: "Points",
        line: 25.5,
        recommendation: "OVER",
        prob: 62,
        conf: "MED" as ConfTier,
      },
      {
        label: "Rebounds",
        line: 11.5,
        recommendation: "OVER",
        prob: 71,
        conf: "HIGH" as ConfTier,
      },
      {
        label: "Assists",
        line: 8.5,
        recommendation: "OVER",
        prob: 64,
        conf: "HIGH" as ConfTier,
      },
    ],
    scoutNote:
      "Jokic's efficiency in the 4th quarter (32.1 pts/100 poss) is unmatched. Triple-double probability tonight vs LAL sits at 61% — he's done it 4 of 5 against them this season.",
  },
  {
    id: "wemby",
    name: "Victor Wembanyama",
    abbr: "VW",
    team: "San Antonio Spurs",
    teamAbbr: "SAS",
    position: "C",
    age: 20,
    tier: "S" as const,
    pts: 22.8,
    reb: 10.6,
    ast: 3.9,
    stl: 1.4,
    blk: 3.6,
    fg: 46.5,
    ft: 79.3,
    tpm: 2.6,
    imageInitials: "VW",
    identitySentence:
      "A creature from another dimension — blocks shots that don't seem blockable.",
    radarStats: { pts: 74, reb: 82, ast: 44, def: 99, eff: 86 },
    trending: "up",
    props: [
      {
        label: "Blocks",
        line: 2.5,
        recommendation: "OVER",
        prob: 74,
        conf: "HIGH" as ConfTier,
      },
      {
        label: "Points",
        line: 22.5,
        recommendation: "OVER",
        prob: 53,
        conf: "COND" as ConfTier,
      },
      {
        label: "3-Pointers",
        line: 2.5,
        recommendation: "OVER",
        prob: 58,
        conf: "MED" as ConfTier,
      },
    ],
    scoutNote:
      "Wemby's block rate (8.7%) is the highest in the shot-blocker era. His offensive game is rapidly catching up — shooting 42% from three on 6+ attempts over the last 15 games.",
  },
  {
    id: "brunson",
    name: "Jalen Brunson",
    abbr: "JB",
    team: "New York Knicks",
    teamAbbr: "NYK",
    position: "PG",
    age: 27,
    tier: "A" as const,
    pts: 28.7,
    reb: 3.6,
    ast: 6.7,
    stl: 0.9,
    blk: 0.2,
    fg: 48.2,
    ft: 84.6,
    tpm: 2.0,
    imageInitials: "JB",
    identitySentence:
      "New York's heartbeat — built for the big stage, thrives when the noise peaks.",
    radarStats: { pts: 91, reb: 38, ast: 78, def: 45, eff: 83 },
    trending: "up",
    props: [
      {
        label: "Points",
        line: 29.5,
        recommendation: "UNDER",
        prob: 58,
        conf: "MED" as ConfTier,
      },
      {
        label: "Assists",
        line: 6.5,
        recommendation: "OVER",
        prob: 62,
        conf: "MED" as ConfTier,
      },
      {
        label: "Points + Assists",
        line: 37.5,
        recommendation: "UNDER",
        prob: 55,
        conf: "COND" as ConfTier,
      },
    ],
    scoutNote:
      "Brunson averages 28.4 in head-to-head vs Boston. His ability to draw fouls (6.8 FTA/game) will be key tonight — if he gets into bonus territory early, Celtic bigs are in foul trouble.",
  },
  {
    id: "edwards",
    name: "Anthony Edwards",
    abbr: "AE",
    team: "Minnesota Timberwolves",
    teamAbbr: "MIN",
    position: "SG",
    age: 22,
    tier: "A" as const,
    pts: 25.9,
    reb: 5.4,
    ast: 5.1,
    stl: 1.3,
    blk: 0.6,
    fg: 46.1,
    ft: 80.7,
    tpm: 3.1,
    imageInitials: "AE",
    identitySentence:
      "Pure athlete, pure showman — when Ant locks in, arenas go silent then explode.",
    radarStats: { pts: 84, reb: 55, ast: 60, def: 72, eff: 78 },
    trending: "up",
    props: [
      {
        label: "Points",
        line: 27.5,
        recommendation: "OVER",
        prob: 65,
        conf: "HIGH" as ConfTier,
      },
      {
        label: "3-Pointers",
        line: 3.5,
        recommendation: "OVER",
        prob: 60,
        conf: "MED" as ConfTier,
      },
      {
        label: "Rebounds",
        line: 4.5,
        recommendation: "UNDER",
        prob: 57,
        conf: "COND" as ConfTier,
      },
    ],
    scoutNote:
      "Edwards is averaging 34.2 in home games over the last 10 — a terrifying number. Tonight vs GSW's 28th-ranked defense, expect isolation dominance and pull-up threes.",
  },
  {
    id: "embiid",
    name: "Joel Embiid",
    abbr: "JE",
    team: "Philadelphia 76ers",
    teamAbbr: "PHI",
    position: "C",
    age: 30,
    tier: "A" as const,
    pts: 34.7,
    reb: 11.0,
    ast: 5.6,
    stl: 1.1,
    blk: 1.7,
    fg: 52.8,
    ft: 85.7,
    tpm: 0.5,
    imageInitials: "JE",
    identitySentence:
      "The most unstoppable post presence since Shaq — when healthy, he's the best player on the floor.",
    radarStats: { pts: 97, reb: 88, ast: 65, def: 80, eff: 91 },
    trending: "neutral",
    props: [
      {
        label: "Points",
        line: 34.5,
        recommendation: "OVER",
        prob: 57,
        conf: "MED" as ConfTier,
      },
      {
        label: "Rebounds",
        line: 10.5,
        recommendation: "OVER",
        prob: 63,
        conf: "MED" as ConfTier,
      },
      {
        label: "Blocks",
        line: 1.5,
        recommendation: "OVER",
        prob: 59,
        conf: "MED" as ConfTier,
      },
    ],
    scoutNote:
      "When Embiid plays 35+ minutes (which he's done in 12 of the last 15), he posts a 38.4/12.2/6.1 line. Health is the only question mark.",
  },
  {
    id: "giannis",
    name: "Giannis Antetokounmpo",
    abbr: "GA",
    team: "Milwaukee Bucks",
    teamAbbr: "MIL",
    position: "PF",
    age: 29,
    tier: "S" as const,
    pts: 30.4,
    reb: 11.5,
    ast: 6.5,
    stl: 1.2,
    blk: 1.1,
    fg: 61.4,
    ft: 65.9,
    tpm: 0.3,
    imageInitials: "GA",
    identitySentence:
      "Human freight train — once he's in motion toward the basket, there is no stopping him.",
    radarStats: { pts: 96, reb: 91, ast: 76, def: 84, eff: 95 },
    trending: "up",
    props: [
      {
        label: "Points",
        line: 30.5,
        recommendation: "OVER",
        prob: 61,
        conf: "MED" as ConfTier,
      },
      {
        label: "Rebounds",
        line: 11.5,
        recommendation: "UNDER",
        prob: 54,
        conf: "COND" as ConfTier,
      },
      {
        label: "Free Throws Made",
        line: 8.5,
        recommendation: "OVER",
        prob: 56,
        conf: "COND" as ConfTier,
      },
    ],
    scoutNote:
      "Giannis vs PHX tonight: averaging 31.4 in this matchup. PHX without Beal has no wing to stick on him. Expect 30+ and a Bucks blowout.",
  },
  {
    id: "luka",
    name: "Luka Doncic",
    abbr: "LD",
    team: "Dallas Mavericks",
    teamAbbr: "DAL",
    position: "PG",
    age: 25,
    tier: "S" as const,
    pts: 33.9,
    reb: 9.2,
    ast: 9.8,
    stl: 1.4,
    blk: 0.5,
    fg: 49.6,
    ft: 76.4,
    tpm: 3.6,
    imageInitials: "LD",
    identitySentence:
      "Maestro with the ball — orchestrates the offense like he's already seen every defense.",
    radarStats: { pts: 96, reb: 84, ast: 96, def: 52, eff: 94 },
    trending: "neutral",
    props: [
      {
        label: "Points",
        line: 33.5,
        recommendation: "OVER",
        prob: 57,
        conf: "MED" as ConfTier,
      },
      {
        label: "Assists",
        line: 9.5,
        recommendation: "UNDER",
        prob: 53,
        conf: "COND" as ConfTier,
      },
      {
        label: "Triple-Double",
        line: 0.5,
        recommendation: "OVER",
        prob: 48,
        conf: "COND" as ConfTier,
      },
    ],
    scoutNote:
      "Luka tonight vs CLE (28-5 at home) is the toughest spot he's been in all season. But he averages 36.2 in this building — the man shows up for the challenge.",
  },
  {
    id: "bam",
    name: "Bam Adebayo",
    abbr: "BA",
    team: "Miami Heat",
    teamAbbr: "MIA",
    position: "C",
    age: 26,
    tier: "A" as const,
    pts: 21.2,
    reb: 10.4,
    ast: 3.5,
    stl: 1.3,
    blk: 0.9,
    fg: 53.8,
    ft: 77.4,
    tpm: 0.1,
    imageInitials: "BA",
    identitySentence:
      "The engine of Heat Culture — unselfish, relentless, the guy every coach wants.",
    radarStats: { pts: 68, reb: 86, ast: 42, def: 82, eff: 75 },
    trending: "up",
    props: [
      {
        label: "Points",
        line: 20.5,
        recommendation: "OVER",
        prob: 58,
        conf: "MED" as ConfTier,
      },
      {
        label: "Rebounds",
        line: 9.5,
        recommendation: "OVER",
        prob: 64,
        conf: "HIGH" as ConfTier,
      },
      {
        label: "Assists",
        line: 3.5,
        recommendation: "UNDER",
        prob: 57,
        conf: "COND" as ConfTier,
      },
    ],
    scoutNote:
      "Bam's defensive versatility is what Miami needs in the playoff push. With Butler back, his efficiency per-touch has actually gone up with Butler drawing attention.",
  },
  {
    id: "haliburton",
    name: "Tyrese Haliburton",
    abbr: "TH",
    team: "Indiana Pacers",
    teamAbbr: "IND",
    position: "PG",
    age: 24,
    tier: "A" as const,
    pts: 20.1,
    reb: 3.7,
    ast: 10.9,
    stl: 1.6,
    blk: 0.4,
    fg: 47.1,
    ft: 83.2,
    tpm: 3.8,
    imageInitials: "TH",
    identitySentence:
      "Pass-first artist — makes everyone on the floor better by making the right read every time.",
    radarStats: { pts: 65, reb: 37, ast: 99, def: 55, eff: 78 },
    trending: "up",
    props: [
      {
        label: "Assists",
        line: 10.5,
        recommendation: "OVER",
        prob: 61,
        conf: "MED" as ConfTier,
      },
      {
        label: "Points",
        line: 19.5,
        recommendation: "OVER",
        prob: 54,
        conf: "COND" as ConfTier,
      },
      {
        label: "3-Pointers",
        line: 3.5,
        recommendation: "OVER",
        prob: 60,
        conf: "MED" as ConfTier,
      },
    ],
    scoutNote:
      "Haliburton's playmaking rate (assist ratio: 44.1%) leads all guards. Pacers run a pace-and-space offense that enables his rhythm threes.",
  },
];

export const MOCK_ANALYSES = [
  {
    id: "a1",
    query: "Brunson props tonight",
    steps: [
      "Parsing proposition: Jalen Brunson props vs BOS",
      "Loading historical H2H data — 14 meetings",
      "Analyzing L5 game logs and efficiency",
      "Cross-referencing Boston defensive matchup ratings",
      "Running Monte Carlo on points distribution (10K sims)",
      "Applying home court and playoff urgency factors",
      "Generating confidence tiers and recommendation",
    ],
    result: {
      title: "Brunson Points — LEAN UNDER 30.5",
      body: "Brunson's H2H average vs Boston is 28.4, and Boston's perimeter defense (4th in DRTG) consistently limits guard scoring. Despite his L5 form (30.2 avg), we lean under. Assists over 6.5 is the better value prop tonight.",
      confidence: "MED" as ConfTier,
      prob: 58,
      signal: "LEAN UNDER · 30.5",
      marketProposition: "Brunson over 30 points vs BOS",
      verdictLabel: "LEAN UNDER",
    },
  },
  {
    id: "a2",
    query: "Will Denver cover -7.5?",
    steps: [
      "Loading DEN vs LAL historical ATS records",
      "Parsing Jokic performance metrics in prime time",
      "Evaluating LAL road defense and adjustment data",
      "Running spread model — 50K simulations",
      "Checking line movement and sharp money signals",
      "Applying live game state adjustment",
      "Generating final spread recommendation",
    ],
    result: {
      title: "DEN -7.5 — STRONG COVER",
      body: "Jokic averaging 32.1 vs LAL with a 61% triple-double probability. Live line has moved to -9.5 with sharp money on Denver. This is a 15+ point game 6/10 times in our model.",
      confidence: "HIGH" as ConfTier,
      prob: 74,
      signal: "DEN COVER · 74%",
      marketProposition: "Denver covers -7.5 vs Lakers",
      verdictLabel: "LEAN OVER",
    },
  },
  {
    id: "a3",
    query: "Best value bet on tonight's slate",
    steps: [
      "Scanning all 6 games on tonight's slate",
      "Running market efficiency analysis",
      "Flagging line movement anomalies",
      "Cross-referencing public money vs sharp money",
      "Applying fatigue and travel adjustment models",
      "Ranking value opportunities by edge percentage",
      "Identifying the highest-edge play",
    ],
    result: {
      title: "Best Value: MIN -6.0 vs GSW",
      body: "Edwards' home dominance (34.2 L10) vs GSW's porous 28th-ranked defense creates maximum edge. Line is 2 points below market efficiency — public money is inflating GSW value based on name recognition, not data.",
      confidence: "HIGH" as ConfTier,
      prob: 72,
      signal: "MIN -6.0 · +7.3% EDGE",
      marketProposition: "Minnesota covers -6 vs Golden State",
      verdictLabel: "LEAN OVER",
    },
  },
];

export const TRENDING_INSIGHTS = [
  { id: "ti1", label: "SGA over 30.5 pts", tag: "HIGH", pct: 67 },
  { id: "ti2", label: "DEN/LAL over 228.0", tag: "MED", pct: 59 },
  { id: "ti3", label: "MIN -6.0 cover", tag: "HIGH", pct: 72 },
  { id: "ti4", label: "Jokic triple-double", tag: "MED", pct: 61 },
  { id: "ti5", label: "BOS/NYK under 222.5", tag: "COND", pct: 54 },
];

export const ARENA_ARTICLES = [
  {
    id: "ar1",
    category: "DEEP DIVE",
    title: "How Jokic's court vision has reached a new statistical frontier",
    excerpt:
      "A frame-by-frame analysis of why Nikola Jokic's passing angles are mechanically unlike anyone who has ever played the position.",
    readTime: "8 min",
    isFeature: true,
  },
  {
    id: "ar2",
    category: "ANALYSIS",
    title: "SGA is becoming the league's most efficient creator",
    excerpt:
      "The OKC guard is averaging 1.14 PPP in isolation — a number that puts him in company with only three other players in the analytics era.",
    readTime: "6 min",
    isFeature: false,
  },
  {
    id: "ar3",
    category: "SCOUTING",
    title: "Wembanyama's third-year leap is happening in real time",
    excerpt:
      "His shot-blocking now extends beyond the paint. His three-point rate suggests a weapon that defenses will not be able to game-plan against.",
    readTime: "5 min",
    isFeature: false,
  },
  {
    id: "ar4",
    category: "POWER RANKINGS",
    title: "Updated power rankings after the trade deadline dust settles",
    excerpt:
      "Boston's depth is historic. Oklahoma City is the sleeper. And one Eastern Conference team is about to make a run nobody is predicting.",
    readTime: "4 min",
    isFeature: false,
  },
  {
    id: "ar5",
    category: "FILM ROOM",
    title: "The play Boston runs in late-clock situations that nobody can stop",
    excerpt:
      "A step-by-step breakdown of the Celtics' ghost screen action — why it works, when they use it, and how opponents have tried to counter it.",
    readTime: "7 min",
    isFeature: false,
  },
];

/* ─── V2 NEW DATA ─── */

export const HOT_TAKES = [
  {
    id: "ht1",
    game: "BOS @ NYK",
    headline: "Brunson drops 35 on a Boston defense with no answer",
    body: "Knicks' home court advantage and Brunson's L5 surge meet a Celtics team on a 3-game skid. This is a statement game.",
    pick: "NYK",
    conf: "HIGH" as ConfTier,
    prob: 68,
    margin: "+4.2",
  },
  {
    id: "ht2",
    game: "LAL @ DEN",
    headline:
      "Jokic triple-double is automatic against a Lakers frontcourt that can't guard the post",
    body: "Jokic has recorded a triple-double in 4 of 5 against LAL this season. Davis can't do it alone.",
    pick: "DEN",
    conf: "MED" as ConfTier,
    prob: 61,
    margin: "+3.1",
  },
  {
    id: "ht3",
    game: "GSW @ MIN",
    headline: "Edwards puts Golden State to bed early — this isn't close",
    body: "Ant is averaging 34.2 in home games over the last 10. Warriors' defense ranks 28th in the league. Mismatch everywhere.",
    pick: "MIN",
    conf: "HIGH" as ConfTier,
    prob: 72,
    margin: "+6.1",
  },
  {
    id: "ht4",
    game: "MIL @ PHX",
    headline: "Giannis and Dame deliver in the desert — Bucks need this one",
    body: "Milwaukee fighting for seeding. Phoenix without Beal. Giannis goes for 30+.",
    pick: "MIL",
    conf: "MED" as ConfTier,
    prob: 57,
    margin: "+2.8",
  },
  {
    id: "ht5",
    game: "DAL @ CLE",
    headline:
      "Cleveland's home record is suffocating — Mavs don't have the depth",
    body: "CLE is 28-5 at home. Without a second star next to Luka, Dallas can't keep up in the second half.",
    pick: "CLE",
    conf: "COND" as ConfTier,
    prob: 52,
    margin: "+1.5",
  },
];

export const NBA_HEADLINES = [
  {
    id: "n1",
    tag: "BREAKING",
    tagColor: "#C8102E",
    headline: "Jimmy Butler cleared to return for Heat playoff push",
    time: "2h ago",
  },
  {
    id: "n2",
    tag: "ANALYSIS",
    tagColor: "#1D428A",
    headline: "Lakers trade deadline acquisition paying dividends in March",
    time: "3h ago",
  },
  {
    id: "n3",
    tag: "AWARD",
    tagColor: "#1D428A",
    headline: "Wembanyama named Western Conference Player of the Week",
    time: "5h ago",
  },
  {
    id: "n4",
    tag: "INJURY",
    tagColor: "#F5A623",
    headline: "Celtics' Porzingis to miss 2-3 weeks with calf strain",
    time: "6h ago",
  },
  {
    id: "n5",
    tag: "RECAP",
    tagColor: "#1D428A",
    headline: "Warriors eyeing playoff seeding with 5-game win streak",
    time: "8h ago",
  },
  {
    id: "n6",
    tag: "STANDINGS",
    tagColor: "#1D428A",
    headline: "Thunder clinch top seed in Western Conference",
    time: "10h ago",
  },
];

export const STAT_LEADERS = {
  points: [
    {
      player: "Shai Gilgeous-Alexander",
      team: "OKC",
      value: 34,
      playerId: 1628983,
    },
    { player: "Jalen Brunson", team: "NYK", value: 31, playerId: 1628973 },
    { player: "Nikola Jokic", team: "DEN", value: 29, playerId: 203999 },
  ],
  rebounds: [
    { player: "Nikola Jokic", team: "DEN", value: 14, playerId: 203999 },
    { player: "Rudy Gobert", team: "MIN", value: 13, playerId: 203497 },
    { player: "Victor Wembanyama", team: "SAS", value: 12, playerId: 1641705 },
  ],
  assists: [
    { player: "Tyrese Haliburton", team: "IND", value: 12, playerId: 1630169 },
    { player: "Nikola Jokic", team: "DEN", value: 11, playerId: 203999 },
    { player: "Jalen Brunson", team: "NYK", value: 9, playerId: 1628973 },
  ],
  steals: [
    { player: "Alex Caruso", team: "OKC", value: 3, playerId: 1627936 },
    {
      player: "Shai Gilgeous-Alexander",
      team: "OKC",
      value: 2,
      playerId: 1628983,
    },
    { player: "De'Aaron Fox", team: "SAS", value: 2, playerId: 1628368 },
  ],
  blocks: [
    { player: "Victor Wembanyama", team: "SAS", value: 4, playerId: 1641705 },
    { player: "Anthony Davis", team: "WAS", value: 3, playerId: 203076 },
    { player: "Bam Adebayo", team: "MIA", value: 2, playerId: 1628389 },
  ],
};

export const ACTIVE_MARKETS = [
  {
    id: "p1",
    proposition: "Brunson over 30 points vs BOS",
    verdict: "LEAN UNDER",
    prob: 42,
    conf: "MED" as ConfTier,
    agreeVotes: 234,
    fadeVotes: 189,
    totalVotes: 423,
    resolvesAt: "10:30 PM ET",
    game: "BOS @ NYK",
    status: "active",
  },
  {
    id: "p2",
    proposition: "Jokic records a triple-double vs LAL",
    verdict: "LEAN OVER",
    prob: 61,
    conf: "HIGH" as ConfTier,
    agreeVotes: 567,
    fadeVotes: 312,
    totalVotes: 879,
    resolvesAt: "When LAL @ DEN ends",
    game: "LAL @ DEN",
    status: "active",
  },
  {
    id: "p3",
    proposition: "Edwards scores 28+ vs GSW",
    verdict: "LEAN OVER",
    prob: 63,
    conf: "HIGH" as ConfTier,
    agreeVotes: 445,
    fadeVotes: 198,
    totalVotes: 643,
    resolvesAt: "12:30 AM ET",
    game: "GSW @ MIN",
    status: "active",
  },
  {
    id: "p4",
    proposition: "Celtics win by 5+ vs Knicks",
    verdict: "LEAN FADE",
    prob: 38,
    conf: "COND" as ConfTier,
    agreeVotes: 156,
    fadeVotes: 201,
    totalVotes: 357,
    resolvesAt: "10:30 PM ET",
    game: "BOS @ NYK",
    status: "active",
  },
];

export const RESOLVED_MARKETS = [
  {
    id: "rp1",
    proposition: "Thunder win by 10+ vs Wizards",
    verdict: "LEAN OVER",
    prob: 74,
    conf: "HIGH" as ConfTier,
    agreeVotes: 892,
    fadeVotes: 156,
    totalVotes: 1048,
    game: "OKC @ WAS",
    status: "resolved",
    result: "CORRECT",
    actualOutcome: "OKC won by 18",
    pointsAwarded: 3,
  },
  {
    id: "rp2",
    proposition: "Luka over 35 points vs PHI",
    verdict: "LEAN OVER",
    prob: 62,
    conf: "MED" as ConfTier,
    agreeVotes: 445,
    fadeVotes: 312,
    totalVotes: 757,
    game: "DAL @ PHI",
    status: "resolved",
    result: "INCORRECT",
    actualOutcome: "Luka had 29 pts",
    pointsAwarded: 0,
  },
  {
    id: "rp3",
    proposition: "Heat/Raptors under 212.5",
    verdict: "LEAN UNDER",
    prob: 55,
    conf: "COND" as ConfTier,
    agreeVotes: 234,
    fadeVotes: 267,
    totalVotes: 501,
    game: "MIA @ TOR",
    status: "resolved",
    result: "CORRECT",
    actualOutcome: "Total: 205",
    pointsAwarded: 8,
  },
];

export const LEADERBOARD = [
  {
    rank: 1,
    username: "MambaForever24",
    points: 847,
    accuracy: 71,
    streak: "W8",
    tier: "Courtside",
  },
  {
    rank: 2,
    username: "JokicVision",
    points: 812,
    accuracy: 68,
    streak: "W5",
    tier: "Courtside",
  },
  {
    rank: 3,
    username: "AnalyticsKing",
    points: 756,
    accuracy: 65,
    streak: "W3",
    tier: "Floor Seat",
  },
  {
    rank: 4,
    username: "NBABrainiac",
    points: 723,
    accuracy: 64,
    streak: "L1",
    tier: "Floor Seat",
  },
  {
    rank: 5,
    username: "HoopScientist",
    points: 698,
    accuracy: 63,
    streak: "W4",
    tier: "Floor Seat",
  },
  {
    rank: 6,
    username: "RimProtector",
    points: 654,
    accuracy: 61,
    streak: "W2",
    tier: "Floor Seat",
  },
  {
    rank: 7,
    username: "TripleDouble",
    points: 621,
    accuracy: 60,
    streak: "L2",
    tier: "Lower Bowl",
  },
  {
    rank: 8,
    username: "ClutchGene",
    points: 589,
    accuracy: 59,
    streak: "W6",
    tier: "Lower Bowl",
  },
  {
    rank: 9,
    username: "SplashZone",
    points: 567,
    accuracy: 58,
    streak: "W1",
    tier: "Lower Bowl",
  },
  {
    rank: 10,
    username: "PaintBeast",
    points: 534,
    accuracy: 57,
    streak: "L1",
    tier: "Lower Bowl",
  },
  {
    rank: 11,
    username: "FloorGeneral",
    points: 512,
    accuracy: 56,
    streak: "W3",
    tier: "Lower Bowl",
  },
  {
    rank: 12,
    username: "DunkContest",
    points: 498,
    accuracy: 55,
    streak: "L3",
    tier: "Lower Bowl",
  },
  {
    rank: 13,
    username: "SixthMan",
    points: 476,
    accuracy: 55,
    streak: "W2",
    tier: "Lower Bowl",
  },
  {
    rank: 14,
    username: "ChasedownBlock",
    points: 445,
    accuracy: 54,
    streak: "W1",
    tier: "Upper Deck",
  },
  {
    rank: 15,
    username: "PickAndPop",
    points: 423,
    accuracy: 53,
    streak: "L1",
    tier: "Upper Deck",
  },
  {
    rank: 16,
    username: "FastBreak",
    points: 401,
    accuracy: 52,
    streak: "W4",
    tier: "Upper Deck",
  },
  {
    rank: 17,
    username: "GlassEater",
    points: 389,
    accuracy: 52,
    streak: "L2",
    tier: "Upper Deck",
  },
  {
    rank: 18,
    username: "DimeDrop",
    points: 367,
    accuracy: 51,
    streak: "W1",
    tier: "Upper Deck",
  },
  {
    rank: 19,
    username: "BuzzerBeater",
    points: 345,
    accuracy: 50,
    streak: "L1",
    tier: "Upper Deck",
  },
  {
    rank: 20,
    username: "PostFade",
    points: 323,
    accuracy: 49,
    streak: "W2",
    tier: "Upper Deck",
  },
];
