export const SEASON_RECORD = {
  wins: 187,
  losses: 142,
  pct: 56.8,
  streak: "W4",
  byConf: { HIGH: { w: 48, l: 19 }, MED: { w: 102, l: 83 }, COND: { w: 37, l: 40 } },
};

export const GAMES = [
  {
    id: "1",
    away: { abbr: "BOS", name: "Celtics", record: "48-16", score: 0, color: "#007A33" },
    home: { abbr: "NYK", name: "Knicks", record: "42-22", score: 0, color: "#F58426" },
    status: "upcoming" as const,
    time: "7:30 PM ET",
    quarter: null,
    clock: null,
    pick: { team: "NYK", conf: "HIGH" as const, prob: 68, margin: "+4.2" },
    correct: null,
    take: "Brunson at home erases any Boston advantage. The Knicks defense has held opponents to 107.2 points in their last 10 home games — and the Garden crowd is a 4-point swing. NYK wins this one comfortably.",
    factors: [
      { name: "Net Rating", val: "+4.2", favor: "NYK", weight: 0.82 },
      { name: "Home Court", val: "+2.8", favor: "NYK", weight: 0.68 },
      { name: "Rest Days", val: "NYK: 2 | BOS: 1", favor: "NYK", weight: 0.55 },
      { name: "Recent Form", val: "NYK 7-3 L10", favor: "NYK", weight: 0.72 },
      { name: "H2H This Season", val: "NYK 2-1", favor: "NYK", weight: 0.60 },
      { name: "Injuries", val: "BOS: none | NYK: Hart Q", favor: "BOS", weight: 0.35 },
    ],
    winProb: [
      { time: "Pre", bos: 46, nyk: 54 },
    ],
    marketOdds: { spread: "NYK -3.5", ml: "NYK -165", total: "O/U 218.5" },
  },
  {
    id: "2",
    away: { abbr: "LAL", name: "Lakers", record: "35-29", score: 87, color: "#552583" },
    home: { abbr: "DEN", name: "Nuggets", record: "44-20", score: 94, color: "#0E2240" },
    status: "live" as const,
    time: null,
    quarter: "Q3",
    clock: "4:22",
    pick: { team: "DEN", conf: "MED" as const, prob: 72, margin: "+5.5" },
    correct: null,
    take: "Jokic is operating at a different level tonight. Denver's pace control is suffocating the Lakers' transition offense — AD is the only counter and he's been held to 14 points on 6-14. The Nuggets close this out.",
    factors: [
      { name: "Net Rating", val: "+6.1", favor: "DEN", weight: 0.88 },
      { name: "Home Court", val: "+3.2", favor: "DEN", weight: 0.65 },
      { name: "Jokic Usage", val: "38.2%", favor: "DEN", weight: 0.91 },
      { name: "LAL Pace Defense", val: "106.4 pts/100", favor: "DEN", weight: 0.77 },
      { name: "H2H Season", val: "DEN 3-1", favor: "DEN", weight: 0.70 },
      { name: "LeBron Minutes", val: "Questionable Q4", favor: "DEN", weight: 0.40 },
    ],
    winProb: [
      { time: "Pre", bos: 38, nyk: 62 },
      { time: "Q1", bos: 44, nyk: 56 },
      { time: "Q2", bos: 36, nyk: 64 },
      { time: "Q3", bos: 28, nyk: 72 },
    ],
    marketOdds: { spread: "DEN -6", ml: "DEN -240", total: "O/U 224.5" },
  },
  {
    id: "3",
    away: { abbr: "GSW", name: "Warriors", record: "32-33", score: 0, color: "#006BB6" },
    home: { abbr: "MEM", name: "Grizzlies", record: "28-37", score: 0, color: "#5D76A9" },
    status: "upcoming" as const,
    time: "10:00 PM ET",
    quarter: null,
    clock: null,
    pick: { team: "GSW", conf: "MED" as const, prob: 57, margin: "+1.8" },
    correct: null,
    take: "Memphis is playing .500 ball this month but the Warriors have Curry back from his ankle. Golden State's movement offense chews up a Memphis defense that surrenders 3-point attempts at league-average rates.",
    factors: [
      { name: "Net Rating", val: "GSW: +1.2", favor: "GSW", weight: 0.52 },
      { name: "Curry Return", val: "Full strength", favor: "GSW", weight: 0.78 },
      { name: "MEM Recent Form", val: "4-6 L10", favor: "GSW", weight: 0.58 },
      { name: "3PT Defense", val: "MEM: 36.1% allowed", favor: "GSW", weight: 0.61 },
      { name: "Rest", val: "Even", favor: "EVEN", weight: 0.50 },
      { name: "Travel", val: "GSW cross-country", favor: "MEM", weight: 0.45 },
    ],
    winProb: [{ time: "Pre", bos: 43, nyk: 57 }],
    marketOdds: { spread: "GSW -1", ml: "GSW -115", total: "O/U 230.5" },
  },
  {
    id: "4",
    away: { abbr: "DAL", name: "Mavericks", record: "29-35", score: 31, color: "#00538C" },
    home: { abbr: "OKC", name: "Thunder", record: "51-13", score: 44, color: "#007AC1" },
    status: "live" as const,
    time: null,
    quarter: "Q1",
    clock: "8:44",
    pick: { team: "OKC", conf: "HIGH" as const, prob: 84, margin: "+11.4" },
    correct: null,
    take: "SGA is dissecting Dallas's defense in real time. The Thunder's pressure defense has forced 6 turnovers already — this is a demolition in progress. Cover your eyes if you're a Mavs fan.",
    factors: [
      { name: "Net Rating", val: "OKC +12.4", favor: "OKC", weight: 0.95 },
      { name: "SGA Form", val: "L5: 32.8 PPG", favor: "OKC", weight: 0.90 },
      { name: "DAL Defense", val: "112.8 DRTG", favor: "OKC", weight: 0.88 },
      { name: "Home Court", val: "+4.1", favor: "OKC", weight: 0.72 },
      { name: "H2H Season", val: "OKC 4-0", favor: "OKC", weight: 0.85 },
      { name: "Doncic Status", val: "OUT (ankle)", favor: "OKC", weight: 0.95 },
    ],
    winProb: [
      { time: "Pre", bos: 16, nyk: 84 },
      { time: "Q1", bos: 12, nyk: 88 },
    ],
    marketOdds: { spread: "OKC -10.5", ml: "OKC -700", total: "O/U 218" },
  },
  {
    id: "5",
    away: { abbr: "PHI", name: "76ers", record: "26-38", score: 114, color: "#006BB6" },
    home: { abbr: "MIA", name: "Heat", record: "31-34", score: 109, color: "#98002E" },
    status: "final" as const,
    time: null,
    quarter: null,
    clock: null,
    pick: { team: "PHI", conf: "COND" as const, prob: 52, margin: "+1.0" },
    correct: true,
    take: "Maxey went nuclear in the fourth — 16 points in the final 4 minutes. The Heat's late-game defense collapsed against his pace. Conditional pick but PHI's guard depth is real.",
    factors: [
      { name: "Net Rating", val: "MIA +1.2", favor: "MIA", weight: 0.52 },
      { name: "Maxey Form", val: "L5: 28.4 PPG", favor: "PHI", weight: 0.74 },
      { name: "MIA Home Def", val: "108.4 DRTG", favor: "MIA", weight: 0.60 },
      { name: "Rest", val: "PHI: 2 days", favor: "PHI", weight: 0.55 },
      { name: "H2H Season", val: "Split 1-1", favor: "EVEN", weight: 0.50 },
      { name: "Embiid Status", val: "DNP (knee)", favor: "MIA", weight: 0.65 },
    ],
    winProb: [
      { time: "Pre", bos: 48, nyk: 52 },
      { time: "Q1", bos: 52, nyk: 48 },
      { time: "Q2", bos: 58, nyk: 42 },
      { time: "Q3", bos: 44, nyk: 56 },
      { time: "Q4", bos: 38, nyk: 62 },
      { time: "Final", bos: 0, nyk: 100 },
    ],
    marketOdds: { spread: "MIA -1", ml: "MIA -115", total: "O/U 222" },
  },
  {
    id: "6",
    away: { abbr: "CLE", name: "Cavaliers", record: "46-18", score: 118, color: "#6F263D" },
    home: { abbr: "CHI", name: "Bulls", record: "22-42", score: 103, color: "#CE1141" },
    status: "final" as const,
    time: null,
    quarter: null,
    clock: null,
    pick: { team: "CLE", conf: "HIGH" as const, prob: 78, margin: "+8.6" },
    correct: true,
    take: "Mitchell put Chicago away in the third. The Cavaliers' defense is the best in the East and the Bulls simply don't have a matchup for it. Exactly as modeled.",
    factors: [
      { name: "Net Rating", val: "CLE +9.8", favor: "CLE", weight: 0.90 },
      { name: "Mitchell Form", val: "L5: 29.2 PPG", favor: "CLE", weight: 0.82 },
      { name: "CLE Defense", val: "104.6 DRTG", favor: "CLE", weight: 0.92 },
      { name: "CHI Pace", val: "97.8", favor: "CLE", weight: 0.72 },
      { name: "H2H Season", val: "CLE 3-0", favor: "CLE", weight: 0.88 },
      { name: "Rest", val: "Even", favor: "EVEN", weight: 0.50 },
    ],
    winProb: [
      { time: "Pre", bos: 22, nyk: 78 },
      { time: "Q1", bos: 28, nyk: 72 },
      { time: "Q2", bos: 22, nyk: 78 },
      { time: "Q3", bos: 14, nyk: 86 },
      { time: "Final", bos: 0, nyk: 100 },
    ],
    marketOdds: { spread: "CLE -7.5", ml: "CLE -310", total: "O/U 220.5" },
  },
];

export const TICKER_ITEMS = [
  { text: "LAL 87 – DEN 94", status: "live" as const, detail: "Q3 4:22 · Jokic: 24/11/9" },
  { text: "DAL 31 – OKC 44", status: "live" as const, detail: "Q1 8:44 · SGA: 18pts" },
  { text: "CLE 118, CHI 103", status: "final" as const, detail: "FINAL · Mitchell: 31pts" },
  { text: "PHI 114, MIA 109", status: "final" as const, detail: "FINAL · Maxey: 34pts" },
  { text: "BOS @ NYK", status: "upcoming" as const, detail: "7:30 PM ET" },
  { text: "GSW @ MEM", status: "upcoming" as const, detail: "10:00 PM ET" },
  { text: "Jokic: 24/11/9 through 3Q", status: "stat" as const, detail: "Triple-double watch" },
  { text: "SGA on pace for 40+", status: "stat" as const, detail: "18 pts in Q1 alone" },
];

export const PLAYERS = [
  {
    id: "sga",
    name: "Shai Gilgeous-Alexander",
    team: "OKC",
    position: "PG",
    number: 2,
    tier: "Generational" as const,
    ovr: 98,
    identity: "The most inevitable scorer in basketball — built different, wired different, plays like the game owes him something.",
    stats: { pts: 31.6, reb: 4.4, ast: 6.4, fg_pct: 53.8 },
    attributes: { insideScoring: 96, outsideScoring: 90, playmaking: 89, athleticism: 88, defending: 85, rebounding: 58 },
    dissection: [
      { category: "OFFENSE", trait: "Deceleration mastery", detail: "Creates 4.2 feet of separation on drives through pure body control. Defenders physically cannot stay with his change of pace without fouling." },
      { category: "PLAYMAKING", trait: "Pick-and-roll IQ", detail: "Reads coverage shifts before the screen arrives. His ability to go early or late on the roll creates impossible decisions for drop bigs." },
      { category: "DEFENSE", trait: "Elite on-ball pressure", detail: "Forces turnovers on 4.1% of opponent possessions — top-5 in the league. His length disrupts without fouling." },
      { category: "PHYSICALITY", trait: "Contact absorption", detail: "Gets to the line on 7.3% of possessions. His body lean and euro-step draw contact from defenders who think they have help." },
    ],
    weaknesses: [
      { trait: "Hard double traps", detail: "Turnover rate spikes from 12% to 18% when hard-doubled above the break with a shot clock under 8 seconds." },
      { trait: "Three-point volume", detail: "Only 4.8 attempts per game. Teams concede the corner three to force him into his half-court game." },
    ],
    scoutQuotes: [
      { quote: "He doesn't blow by you — he gets you moving the wrong direction before you realize it. By the time you recover, he's already at the line.", attribution: "Western Conference assistant coach" },
      { quote: "The deceleration is unprecedented. Not Nash, not CP3 — this is something new. Closest comp is a prime Harden but without the moral injury.", attribution: "NBA front office executive" },
    ],
    scoutingReport: "There is a version of watching Shai Gilgeous-Alexander where you convince yourself you can stop him. The hesitation is coming — you know it. The pull-up is coming — you've seen the film. And then he does it anyway, the ball goes in, and 20,000 people in Oklahoma City lose their minds.\n\nWhat separates SGA from every other scorer in the league is the authenticity of his pace. He plays at 70% until the exact moment he needs 100% — and that moment arrives like a switch flipping. Defenders who key on the deceleration get beaten backdoor. Defenders who play off get dropped with a mid-range that doesn't care about your feelings.\n\nThe Thunder built their entire system around giving SGA the space to operate. It's not just talent. It's ecosystem design. And right now, that ecosystem is producing the best basketball we've seen from a guard in a decade.",
    tags: ["ASCENDING", "CLUTCH", "GENERATIONAL", "MVPFAVORITE"],
    recentGames: [
      { date: "Mar 14", opp: "DAL", result: "W", pts: 38, reb: 5, ast: 7, plusMinus: 22 },
      { date: "Mar 12", opp: "DEN", result: "W", pts: 29, reb: 4, ast: 8, plusMinus: 11 },
      { date: "Mar 10", opp: "MEM", result: "W", pts: 35, reb: 6, ast: 5, plusMinus: 18 },
      { date: "Mar 8", opp: "LAL", result: "W", pts: 31, reb: 3, ast: 9, plusMinus: 14 },
      { date: "Mar 6", opp: "POR", result: "W", pts: 26, reb: 7, ast: 6, plusMinus: 16 },
    ],
    tonightProps: [
      { stat: "Points", line: 30.5, prob: 68, conf: "MED" as const, l5: 31.8, seasonAvg: 31.6, opponentDef: "DAL allows 112.8 to guards", lean: "OVER" as const },
      { stat: "Assists", line: 5.5, prob: 72, conf: "HIGH" as const, l5: 7.0, seasonAvg: 6.4, opponentDef: "DAL 22nd in assist containment", lean: "OVER" as const },
      { stat: "Rebounds", line: 4.5, prob: 44, conf: "COND" as const, l5: 5.0, seasonAvg: 4.4, opponentDef: "Neutral", lean: "PUSH" as const },
    ],
  },
  {
    id: "jokic",
    name: "Nikola Jokic",
    team: "DEN",
    position: "C",
    number: 15,
    tier: "Generational" as const,
    ovr: 99,
    identity: "The greatest passing big man in basketball history — redefines the position every time he touches the ball.",
    stats: { pts: 26.4, reb: 12.1, ast: 9.0, fg_pct: 57.6 },
    attributes: { insideScoring: 95, outsideScoring: 72, playmaking: 99, athleticism: 68, defending: 74, rebounding: 98 },
    dissection: [
      { category: "PLAYMAKING", trait: "Omniscient vision", detail: "Sees passing lanes that don't exist yet. His pocket passes from the post find cutters in spaces defenders didn't know they'd vacated." },
      { category: "OFFENSE", trait: "Post-up efficiency", detail: "1.24 PPP on post-up possessions — best in the NBA for a big. Shooting 62% in the paint with either hand equally." },
      { category: "PHYSICALITY", trait: "Strength leverage", detail: "Despite below-average athleticism metrics, uses body position and timing to absorb contact and finish at 75% in traffic." },
      { category: "DEFENSE", trait: "Rotational IQ", detail: "Not a rim protector by athleticism but reads rotations beautifully. Positioned correctly 91% of the time according to tracking data." },
    ],
    weaknesses: [
      { trait: "Transition defense", detail: "Gets caught in no-man's land running back. Teams that push pace force him into uncomfortable sprint-back situations." },
      { trait: "Pick-and-roll defense", detail: "Hedging leaves gaps. Elite screen-and-roll teams (BOS, NYK) exploit the drop coverage by shooting over it." },
    ],
    scoutQuotes: [
      { quote: "I've been scouting for 22 years. I've never had to write a report that started with 'he already knows what you're going to do.'", attribution: "Western Conference scout" },
      { quote: "The triple-double thing undersells it. What he does in the fourth quarter — the reads, the pace control — that's a different sport.", attribution: "Championship-winning head coach" },
    ],
    scoutingReport: "Nikola Jokic does not play basketball the way basketball is played. He plays a slower, more deliberate, more devastating version of the game where every possession is a chess problem and he's already three moves ahead.\n\nThe triple-double production is a floor, not a ceiling. On a given night Jokic might go 30/17/13 and you still feel like you're underselling it because of the quality of each possession — the assist that turned a 2-point play into a layup, the rebound that started a fast break, the shot fake that drew the foul with 0.8 seconds left on the shot clock.\n\nThe Nuggets have built their offense entirely around his gravity and it has produced the most efficient half-court offense in NBA history over the last three seasons. There is no answer for it.",
    tags: ["CLUTCH", "MVPCHASER", "HISTORICALPACE", "SYSTEM"],
    recentGames: [
      { date: "Mar 14", opp: "LAL", result: "W", pts: 28, reb: 14, ast: 11, plusMinus: 18 },
      { date: "Mar 12", opp: "POR", result: "W", pts: 24, reb: 16, ast: 8, plusMinus: 14 },
      { date: "Mar 10", opp: "UTA", result: "W", pts: 30, reb: 11, ast: 12, plusMinus: 22 },
      { date: "Mar 8", opp: "PHX", result: "L", pts: 22, reb: 13, ast: 7, plusMinus: -4 },
      { date: "Mar 6", opp: "SAC", result: "W", pts: 27, reb: 10, ast: 9, plusMinus: 11 },
    ],
    tonightProps: [
      { stat: "Points", line: 25.5, prob: 62, conf: "MED" as const, l5: 26.2, seasonAvg: 26.4, opponentDef: "LAL allows 104.2 to bigs", lean: "OVER" as const },
      { stat: "Rebounds", line: 11.5, prob: 74, conf: "HIGH" as const, l5: 12.8, seasonAvg: 12.1, opponentDef: "LAL 28th in rebound containment", lean: "OVER" as const },
      { stat: "Assists", line: 8.5, prob: 66, conf: "MED" as const, l5: 9.4, seasonAvg: 9.0, opponentDef: "LAL 19th in assist containment", lean: "OVER" as const },
    ],
  },
  {
    id: "brunson",
    name: "Jalen Brunson",
    team: "NYK",
    position: "PG",
    number: 11,
    tier: "All-World" as const,
    ovr: 91,
    identity: "The most complete point guard in the Eastern Conference — and he knows it.",
    stats: { pts: 28.4, reb: 3.8, ast: 7.2, fg_pct: 48.1 },
    attributes: { insideScoring: 88, outsideScoring: 85, playmaking: 90, athleticism: 72, defending: 68, rebounding: 45 },
    dissection: [
      { category: "OFFENSE", trait: "Mid-range assassin", detail: "Brunson's pull-up jumper from 10-16 feet is the most reliable shot in the NBA. Defenders know it's coming. It doesn't matter." },
      { category: "PLAYMAKING", trait: "Pick-and-roll maestro", detail: "Reads the defense before the screen arrives. His pocket passes to rolling bigs create easy buckets out of nothing." },
      { category: "DEFENSE", trait: "Positional discipline", detail: "Won't get cooked off the dribble. Limited by size against bigger guards but compensates with positioning and anticipation." },
      { category: "PHYSICALITY", trait: "Contact finishing", detail: "Absorbs contact at the rim better than guards 4 inches taller. Elite body control in traffic." },
    ],
    weaknesses: [
      { trait: "Size limitations", detail: "At 6'1\", switchable defenses with length cause problems. Can be hunted in playoff matchups." },
      { trait: "Three-point volume", detail: "Only 4.2 attempts per game from deep. Teams sag off and dare him to shoot." },
    ],
    scoutQuotes: [
      { quote: "You can't game-plan for a guy who makes the right read every time. You can only hope he misses.", attribution: "Eastern Conference scout" },
      { quote: "Best footwork for a guard since Nash. The mid-range game is vintage, but the efficiency is modern.", attribution: "NBA front office exec" },
    ],
    scoutingReport: "Jalen Brunson is the most underrated superstar in the NBA — a categorically incorrect take that somehow persists despite him dragging the Knicks to consecutive playoff runs on pure basketball will.\n\nThe secret is that nothing Brunson does looks spectacular. He doesn't dunk over people. He doesn't post 50-point games. He just makes the right play, at the right moment, with the right efficiency, every night for 38 minutes.\n\nAt the Garden, where the crowd feeds into his measured intensity, Brunson is virtually unguardable. His step-back mid-range has a 58% hit rate at home — a number that makes shooting coaches question their entire belief system.",
    tags: ["CLUTCH", "ASCENDING", "FRANCHISE-CHANGER"],
    recentGames: [
      { date: "Mar 14", opp: "MIA", result: "W", pts: 34, reb: 4, ast: 8, plusMinus: 12 },
      { date: "Mar 12", opp: "CHA", result: "W", pts: 31, reb: 3, ast: 6, plusMinus: 8 },
      { date: "Mar 10", opp: "DET", result: "W", pts: 27, reb: 5, ast: 9, plusMinus: 15 },
      { date: "Mar 8", opp: "IND", result: "L", pts: 33, reb: 2, ast: 7, plusMinus: -3 },
      { date: "Mar 6", opp: "ORL", result: "W", pts: 24, reb: 4, ast: 11, plusMinus: 7 },
    ],
    tonightProps: [
      { stat: "Points", line: 29.5, prob: 42, conf: "MED" as const, l5: 29.8, seasonAvg: 28.4, opponentDef: "BOS top-5 defense (104.1 DRTG)", lean: "UNDER" as const },
      { stat: "Assists", line: 6.5, prob: 60, conf: "MED" as const, l5: 8.2, seasonAvg: 7.2, opponentDef: "BOS 8th in assist containment", lean: "OVER" as const },
      { stat: "Rebounds", line: 3.5, prob: 55, conf: "COND" as const, l5: 3.6, seasonAvg: 3.8, opponentDef: "Neutral", lean: "PUSH" as const },
    ],
  },
  {
    id: "tatum",
    name: "Jayson Tatum",
    team: "BOS",
    position: "SF",
    number: 0,
    tier: "All-World" as const,
    ovr: 93,
    identity: "The most versatile two-way wing in basketball — a walking mismatch at both ends.",
    stats: { pts: 27.1, reb: 8.6, ast: 4.7, fg_pct: 45.8 },
    attributes: { insideScoring: 84, outsideScoring: 88, playmaking: 78, athleticism: 82, defending: 86, rebounding: 75 },
    dissection: [
      { category: "OFFENSE", trait: "Shot creation", detail: "Generates 5.8 clean pull-up looks per game — third highest in the league. His Kobe-step isolations are unguardable from the elbow." },
      { category: "DEFENSE", trait: "Versatile coverage", detail: "Guards 1-through-4 without switching issues. His combination of length, footwork, and anticipation makes him elite at the point of attack." },
      { category: "PLAYMAKING", trait: "Drive and dish", detail: "When teams load up on his pull-up, he finds cutters at 48% conversion — improving every season." },
      { category: "PHYSICALITY", trait: "Offensive rebounding", detail: "8.6 rebounds per game includes 2.1 offensive — elite for a wing. Creates second-chance points out of nothing." },
    ],
    weaknesses: [
      { trait: "Volume efficiency dips", detail: "When crossing 22+ field goal attempts, shooting percentage drops to 41%. Ball-stopping tendencies increase late in games." },
      { trait: "Free throw consistency", detail: "77% from the line — acceptable but exploitable in clutch moments. Teams foul him strategically in close games." },
    ],
    scoutQuotes: [
      { quote: "He's the best two-way wing since LeBron in Cleveland. I know that's a bold statement. I'm standing by it.", attribution: "Eastern Conference head coach" },
      { quote: "The Kobe step — I've watched that shot chart and I still can't tell you how to stop it. He just rises above everything.", attribution: "Western Conference defensive coordinator" },
    ],
    scoutingReport: "Jayson Tatum is what happens when you take a player with Carmelo Anthony's offensive instincts and give him Kevin Garnett's defensive education and Paul Pierce's winning mentality. The result is the best Boston Celtic since the original big three.\n\nHis continued improvement is the most underappreciated story in the NBA. Every offseason Tatum adds something specific — the 3-point range, the playmaking from the elbow, the defensive switching ability. He's not getting better by accident.\n\nIn the playoffs, Tatum elevates. His usage rate goes up, his efficiency holds, and his ability to manufacture points in half-court sets against locked-in defenses is what separates him from the league's merely excellent wings.",
    tags: ["CLUTCH", "ASCENDING", "TWOWAYWING", "ELITEDEFENDER"],
    recentGames: [
      { date: "Mar 14", opp: "TOR", result: "W", pts: 29, reb: 10, ast: 5, plusMinus: 16 },
      { date: "Mar 12", opp: "ORL", result: "W", pts: 24, reb: 9, ast: 4, plusMinus: 8 },
      { date: "Mar 10", opp: "WAS", result: "W", pts: 32, reb: 7, ast: 6, plusMinus: 24 },
      { date: "Mar 8", opp: "PHI", result: "L", pts: 21, reb: 8, ast: 3, plusMinus: -7 },
      { date: "Mar 6", opp: "CHI", result: "W", pts: 28, reb: 11, ast: 5, plusMinus: 19 },
    ],
    tonightProps: [
      { stat: "Points", line: 26.5, prob: 58, conf: "MED" as const, l5: 26.8, seasonAvg: 27.1, opponentDef: "NYK 11th in perimeter defense", lean: "OVER" as const },
      { stat: "Rebounds", line: 8.5, prob: 54, conf: "COND" as const, l5: 9.0, seasonAvg: 8.6, opponentDef: "NYK 14th in wing rebound containment", lean: "OVER" as const },
      { stat: "Assists", line: 4.5, prob: 48, conf: "COND" as const, l5: 4.6, seasonAvg: 4.7, opponentDef: "Neutral", lean: "PUSH" as const },
    ],
  },
  {
    id: "edwards",
    name: "Anthony Edwards",
    team: "MIN",
    position: "SG",
    number: 5,
    tier: "All-World" as const,
    ovr: 90,
    identity: "The most explosive two-guard in basketball — 6'4\", 225 pounds of will and athleticism.",
    stats: { pts: 29.6, reb: 5.1, ast: 3.6, fg_pct: 46.2 },
    attributes: { insideScoring: 90, outsideScoring: 88, playmaking: 72, athleticism: 98, defending: 80, rebounding: 60 },
    dissection: [
      { category: "OFFENSE", trait: "Downhill destruction", detail: "Attacks the rim at 40% of his shot attempts — highest rate among shooting guards. His combination of speed and body creates impossible angles for defenders." },
      { category: "PHYSICALITY", trait: "Strength on drives", detail: "225 pounds of muscle used intentionally. Bends defenders with shoulder-first drives and finishes through contact at 68% inside 5 feet." },
      { category: "OFFENSE", trait: "Step-back three", detail: "Has expanded his pull-up game to include a reliable off-dribble three from 26-28 feet. Now defenses can't sag to stop the drive." },
      { category: "DEFENSE", trait: "On-ball intensity", detail: "When locked in, creates 3.2 deflections per game — elite for his position. His length and quickness allow him to contain both guards and wings." },
    ],
    weaknesses: [
      { trait: "High-stunt coverages", detail: "Jab-step and reach-in help from behind disrupts his drive timing. Over-aggressive bigs who sag and cut off the lane give him problems." },
      { trait: "Late-clock half-court", detail: "Turnover rate climbs to 16% in possessions under 8 seconds. His isolation game against set defenses is still developing." },
    ],
    scoutQuotes: [
      { quote: "You can scout everything he does. You can watch every drive, every step-back. He still does it to you. That's what makes him special.", attribution: "Western Conference defensive coordinator" },
      { quote: "He's 22 playing with the physicality of a veteran and the fearlessness of someone who hasn't lost enough yet. Wait until he learns how to win.", attribution: "Championship-winning head coach" },
    ],
    scoutingReport: "Anthony Edwards arrived in the NBA with a freight train's momentum and has somehow gotten faster. The step-back three he's added this season has changed his entire offensive profile — he's no longer a guy you can load up on the drive. Now you have to guard him everywhere.\n\nWhat makes Edwards special is the authenticity of his physicality. His 225-pound frame isn't defensive bulk — it's offensive weaponry. When he sets his shoulder and drives baseline, defenders who try to take the charge are making a dangerous choice.\n\nMinnesota built a legitimate contender around his energy, and now Edwards is learning what it means to be a closer. The development arc is steep and it's still going up.",
    tags: ["ASCENDING", "EXPLOSIVE", "FRANCHISE-CHANGER", "TWOWAYWING"],
    recentGames: [
      { date: "Mar 14", opp: "SAC", result: "W", pts: 32, reb: 6, ast: 4, plusMinus: 9 },
      { date: "Mar 12", opp: "PHX", result: "L", pts: 28, reb: 5, ast: 3, plusMinus: -5 },
      { date: "Mar 10", opp: "LAC", result: "W", pts: 35, reb: 4, ast: 5, plusMinus: 14 },
      { date: "Mar 8", opp: "HOU", result: "W", pts: 26, reb: 7, ast: 3, plusMinus: 8 },
      { date: "Mar 6", opp: "OKC", result: "L", pts: 22, reb: 5, ast: 2, plusMinus: -11 },
    ],
    tonightProps: [],
  },
  {
    id: "doncic",
    name: "Luka Doncic",
    team: "DAL",
    position: "PG",
    number: 77,
    tier: "Generational" as const,
    ovr: 97,
    identity: "A basketball genius operating in a different dimension — the game slows down when he touches it.",
    stats: { pts: 33.9, reb: 9.2, ast: 9.8, fg_pct: 48.7 },
    attributes: { insideScoring: 88, outsideScoring: 94, playmaking: 97, athleticism: 76, defending: 62, rebounding: 82 },
    dissection: [
      { category: "PLAYMAKING", trait: "High-gravity creation", detail: "Draws 2.3 defenders on every play he initiates. The gravity he creates for teammates is the highest in the league." },
      { category: "OFFENSE", trait: "Step-back three mastery", detail: "42.8% from three on pull-up attempts — a statistical impossibility for someone taking 7.2 such shots per game." },
      { category: "PLAYMAKING", trait: "Blitz immunity", detail: "When doubled before the pass, completes pass within 0.4 seconds on average. Elite at recognizing and exploiting traps." },
      { category: "PHYSICALITY", trait: "Contact drawing", detail: "6.8 free throw attempts per game — among the highest for a guard. His body control draws contact on shots that looked like misses." },
    ],
    weaknesses: [
      { trait: "Defensive engagement", detail: "Willingness to compete defensively varies by game. Elite offenses target him systematically and he doesn't always fight back." },
      { trait: "Conditioning late games", detail: "Efficiency dips in fourth quarters when teams push the pace and force him to use full energy. L5 Q4 FG%: 38%." },
    ],
    scoutQuotes: [
      { quote: "His feel for the game is a once-in-a-generation thing. The step-back, the vision, the clutch shooting — it's all connected to basketball intelligence you can't teach.", attribution: "Hall of Fame point guard" },
      { quote: "Every team has a Luka plan. The plan always fails. I've watched six different teams try to blitz him this season. He found the answer within two plays every time.", attribution: "Western Conference scout" },
    ],
    scoutingReport: "Luka Doncic is playing the most efficient brand of high-volume scoring in NBA history — a statement that requires unpacking because it sounds hyperbolic until you check the numbers and realize it's technically conservative.\n\nThe step-back three is now so reliable that teams can't commit to stopping it without giving up driving lanes. His combination of size (6'7\") and court vision creates a mismatch problem that has no answer in modern basketball.\n\nWith Kyrie Irving's availability uncertain, Doncic has had to do even more in Dallas — a situation that would break most players and instead seems to be producing his best basketball.",
    tags: ["MVPFAVORITE", "CLUTCH", "HISTORICALPACE", "GENERATIONAL"],
    recentGames: [
      { date: "Mar 14", opp: "OKC", result: "L", pts: 0, reb: 0, ast: 0, plusMinus: 0 },
      { date: "Mar 12", opp: "DEN", result: "W", pts: 38, reb: 11, ast: 12, plusMinus: 6 },
      { date: "Mar 10", opp: "PHX", result: "W", pts: 41, reb: 8, ast: 9, plusMinus: 14 },
      { date: "Mar 8", opp: "LAC", result: "W", pts: 29, reb: 10, ast: 11, plusMinus: 3 },
      { date: "Mar 6", opp: "SAC", result: "L", pts: 34, reb: 7, ast: 8, plusMinus: -5 },
    ],
    tonightProps: [],
  },
  {
    id: "maxey",
    name: "Tyrese Maxey",
    team: "PHI",
    position: "PG",
    number: 0,
    tier: "Franchise" as const,
    ovr: 86,
    identity: "The fastest guard in basketball — in terms of both feet and decision-making.",
    stats: { pts: 25.9, reb: 3.7, ast: 6.2, fg_pct: 45.3 },
    attributes: { insideScoring: 82, outsideScoring: 84, playmaking: 80, athleticism: 92, defending: 72, rebounding: 42 },
    dissection: [
      { category: "OFFENSE", trait: "Transition pace", detail: "Leads the league in transition points per game (8.4). His burst off the catch and first-step explosion are elite." },
      { category: "OFFENSE", trait: "Catch-and-shoot efficiency", detail: "47.2% on spot-up threes — elite for someone getting to that level off the dribble as well. Defenders can't sag off." },
      { category: "PLAYMAKING", trait: "Drive and kick", detail: "Creates 4.2 open threes per game for teammates through his attacking style. A natural playmaker despite his scorer identity." },
      { category: "PHYSICALITY", trait: "Motor and energy", detail: "Elite conditioning allows him to maintain sprint-level pace in the fourth quarter. Teams that push pace against PHI get worn down." },
    ],
    weaknesses: [
      { trait: "Half-court creation", detail: "Against set defenses in late-game situations, relies heavily on the pull-up. Shot selection can deteriorate under pressure." },
      { trait: "Size disadvantage", detail: "At 6'2\", larger guards can exploit him defensively. Teams target him in pick-and-roll coverage in the playoffs." },
    ],
    scoutQuotes: [
      { quote: "He plays at a pace that most players can't even read. By the time you figure out what he's doing, he's already at the rim.", attribution: "Eastern Conference defensive coordinator" },
      { quote: "Maxey with Embiid is elite. Maxey without Embiid is still very, very good. That's the growth story of the year.", attribution: "NBA front office exec" },
    ],
    scoutingReport: "Tyrese Maxey's emergence as a primary creator in Philadelphia has been one of the most important developmental stories of the last three seasons. When Embiid's knee forced extended absences, Maxey answered the call with consistent 28-point performances against playoff-caliber defenses.\n\nHis game is built on pace. He converts fast break opportunities at 68% — a number that speaks to decision-making speed as much as athleticism. His ability to see the finish before the play develops is what separates him from similarly athletic guards.\n\nThe three-point shooting is real. 47.2% on catch-and-shoot looks means defenses can't afford to give him daylight, which opens driving lanes, which creates more threes. The virtuous cycle is alive and well.",
    tags: ["ASCENDING", "RISING", "CLUTCH", "NEXTGEN"],
    recentGames: [
      { date: "Mar 14", opp: "MIA", result: "W", pts: 34, reb: 4, ast: 7, plusMinus: 11 },
      { date: "Mar 12", opp: "WAS", result: "W", pts: 28, reb: 3, ast: 6, plusMinus: 14 },
      { date: "Mar 10", opp: "DET", result: "W", pts: 26, reb: 5, ast: 8, plusMinus: 9 },
      { date: "Mar 8", opp: "CHI", result: "L", pts: 22, reb: 2, ast: 5, plusMinus: -6 },
      { date: "Mar 6", opp: "CLE", result: "L", pts: 31, reb: 4, ast: 6, plusMinus: -8 },
    ],
    tonightProps: [],
  },
  {
    id: "mitchell",
    name: "Donovan Mitchell",
    team: "CLE",
    position: "SG",
    number: 45,
    tier: "All-World" as const,
    ovr: 89,
    identity: "A relentless attacking guard built for playoff basketball — the bigger the game, the better he plays.",
    stats: { pts: 28.6, reb: 4.5, ast: 5.8, fg_pct: 46.4 },
    attributes: { insideScoring: 88, outsideScoring: 86, playmaking: 78, athleticism: 86, defending: 80, rebounding: 52 },
    dissection: [
      { category: "OFFENSE", trait: "Pull-up midrange", detail: "Sixth-highest efficiency from pull-up midrange in the NBA. Created entirely by footwork and body control, not athleticism alone." },
      { category: "OFFENSE", trait: "Clutch scoring", detail: "48.2% from the field in the final 5 minutes of close games (within 5 pts). The moment does not accelerate his decision-making." },
      { category: "DEFENSE", trait: "On-ball tenacity", detail: "Creates 2.8 deflections per game and draws charges at a top-10 rate. His defensive intensity raises the Cavaliers' floor." },
      { category: "PLAYMAKING", trait: "Pace management", detail: "Controls Cleveland's half-court offense with precision. His ability to speed up or slow down the game based on advantage is elite." },
    ],
    weaknesses: [
      { trait: "Three-point consistency", detail: "Volume shooter from three (6.8 attempts) but only 37.1% — creates inefficiency on cold nights when the drive isn't working." },
      { trait: "Decision making in blitzes", detail: "When doubled off the pick-and-roll, turnover rate climbs to 15%. Elite teams trap him systematically." },
    ],
    scoutQuotes: [
      { quote: "Playoff Spida is the best version of him and you still can't prepare for it. He finds shots in spaces that don't exist.", attribution: "Eastern Conference scout" },
      { quote: "Cleveland is a championship contender because of him. Not around him — because of him. There's a difference.", attribution: "Eastern Conference head coach" },
    ],
    scoutingReport: "Donovan Mitchell has quietly assembled one of the most complete offensive games in the East — a fact obscured by playing in Cleveland and next to an elite defensive system that makes everything look easier than it is.\n\nThe clutch shooting is the defining characteristic. Mitchell doesn't shrink in big moments — he actually becomes more efficient, a neurological response to pressure that only the elite scorers in the game possess.\n\nWith Cleveland built around a top-three defense and Mitchell as their primary creator, the Cavaliers are a genuine Finals threat. And Mitchell in the playoffs is a different animal than Mitchell in February.",
    tags: ["CLUTCH", "ASCENDING", "PLAYOFFPERFORMER", "ELITEDEFENDER"],
    recentGames: [
      { date: "Mar 14", opp: "CHI", result: "W", pts: 31, reb: 5, ast: 6, plusMinus: 18 },
      { date: "Mar 12", opp: "DET", result: "W", pts: 27, reb: 4, ast: 7, plusMinus: 12 },
      { date: "Mar 10", opp: "WAS", result: "W", pts: 29, reb: 6, ast: 5, plusMinus: 21 },
      { date: "Mar 8", opp: "TOR", result: "W", pts: 33, reb: 3, ast: 8, plusMinus: 9 },
      { date: "Mar 6", opp: "PHI", result: "W", pts: 24, reb: 5, ast: 6, plusMinus: 8 },
    ],
    tonightProps: [],
  },
  {
    id: "fox",
    name: "De'Aaron Fox",
    team: "SAC",
    position: "PG",
    number: 5,
    tier: "Franchise" as const,
    ovr: 85,
    identity: "The fastest guard in the open court — his pace in transition is a cheat code that teams still haven't solved.",
    stats: { pts: 25.2, reb: 3.6, ast: 7.8, fg_pct: 48.4 },
    attributes: { insideScoring: 88, outsideScoring: 72, playmaking: 86, athleticism: 96, defending: 74, rebounding: 42 },
    dissection: [
      { category: "OFFENSE", trait: "Transition dominance", detail: "9.2 points per game in transition — first in the NBA. His first step off defensive rebounds is the fastest in the league." },
      { category: "PLAYMAKING", trait: "Push-pace facilitation", detail: "Creates 5.4 open looks per game in transition for teammates. His read-and-go ability is elite." },
      { category: "OFFENSE", trait: "Floater game", detail: "68% in the restricted area including off the pull-up floater. Defenders give him the mid-drive layup and pay the price." },
      { category: "DEFENSE", trait: "On-ball quickness", detail: "Lateral quickness testing puts him in top 2% of players. Can contain most guards without help." },
    ],
    weaknesses: [
      { trait: "Half-court shot creation", detail: "Against set defenses he relies on the drive. When rim protection eliminates that, his efficiency drops to 38% FG." },
      { trait: "Three-point shooting", detail: "Only 32.8% from three on 4.4 attempts. Teams sag off aggressively and eliminate his driving lanes." },
    ],
    scoutQuotes: [
      { quote: "In transition he's ungovernable. You simply cannot stop him if he gets ahead of the defense. The problem is stopping him from getting ahead.", attribution: "Western Conference assistant coach" },
      { quote: "Sacramento built around his pace and it works. The question is whether it works in the playoffs when everything slows down.", attribution: "Western Conference scout" },
    ],
    scoutingReport: "De'Aaron Fox is the most impactful transition player since a prime LeBron James — a statement that requires context but holds up under examination. His first two steps off a defensive rebound create a burst that simply cannot be matched by any combination of help defense schemes.\n\nSacramento's offense lives and dies by whether Fox can get into transition. When they push the pace, they're a top-five offense. When the game slows to half-court sets, they drop toward league-average territory.\n\nFox's continued improvement from three would transform this team into a perennial contender. The shooting mechanics look better in recent practice footage — an upgrade that could be the final piece.",
    tags: ["ASCENDING", "FRANCHISE-CHANGER", "TRANSITION", "UNDERRATED"],
    recentGames: [
      { date: "Mar 14", opp: "MIN", result: "L", pts: 28, reb: 4, ast: 9, plusMinus: -9 },
      { date: "Mar 12", opp: "PHX", result: "W", pts: 31, reb: 3, ast: 8, plusMinus: 7 },
      { date: "Mar 10", opp: "LAC", result: "W", pts: 24, reb: 5, ast: 7, plusMinus: 4 },
      { date: "Mar 8", opp: "UTA", result: "W", pts: 22, reb: 4, ast: 11, plusMinus: 12 },
      { date: "Mar 6", opp: "DAL", result: "W", pts: 27, reb: 3, ast: 8, plusMinus: 6 },
    ],
    tonightProps: [],
  },
  {
    id: "brown",
    name: "Jaylen Brown",
    team: "BOS",
    position: "SG",
    number: 7,
    tier: "Franchise" as const,
    ovr: 84,
    identity: "An ascending two-way guard who makes every Boston win look inevitable.",
    stats: { pts: 23.0, reb: 5.5, ast: 3.8, fg_pct: 49.2 },
    attributes: { insideScoring: 86, outsideScoring: 78, playmaking: 65, athleticism: 92, defending: 82, rebounding: 68 },
    dissection: [
      { category: "OFFENSE", trait: "Catch-and-shoot efficiency", detail: "49.2% FG on off-ball cuts and catch-and-shoot opportunities. His off-ball movement is elite and underappreciated." },
      { category: "DEFENSE", trait: "Perimeter lock-down", detail: "Holds opposing wings to 38.2% from three when guarding them throughout the possession. Top-10 perimeter defender." },
      { category: "PHYSICALITY", trait: "Athleticism for contact", detail: "Absorbs contact on drives and finishes at 64% through contact — elite for a wing." },
      { category: "OFFENSE", trait: "Spot-up gravity", detail: "Creates 4.8 open looks for Tatum per game through spacing and cuts. The system works because of Brown's discipline." },
    ],
    weaknesses: [
      { trait: "Ball-handling under pressure", detail: "Turnover rate of 14% when the primary ball-handler — above average. Better as a secondary option." },
      { trait: "Shot creation from isolation", detail: "Only 38% from isolation possessions — struggles against elite defenders with no screen." },
    ],
    scoutQuotes: [
      { quote: "He's not the second option — he's a first option playing a second-option role. Boston would be 10 games worse without him.", attribution: "Eastern Conference scout" },
      { quote: "His athleticism combined with the shooting makes him one of the hardest matchups in the league. Wings can't guard him, smaller guards can't control him.", attribution: "Western Conference defensive coordinator" },
    ],
    scoutingReport: "Jaylen Brown's evolution from raw athlete to elite two-way wing represents one of the great developmental arcs of the last five years. In Boston's system, he's found the perfect role — secondary creator who becomes the primary option when defenses overload on Tatum.\n\nThe shooting improvement is the story. Brown went from a liability from three to a legitimate spacing threat, opening the entire Boston offense in ways that only become visible when you watch without the ball.\n\nHis defense is criminally underrated nationally. Ask any Eastern Conference guard about facing Brown — the answer is always the same. He makes everything hard.",
    tags: ["TWOWAYWING", "ASCENDING", "SYSTEMFIT", "ELITEDEFENDER"],
    recentGames: [
      { date: "Mar 14", opp: "TOR", result: "W", pts: 26, reb: 6, ast: 4, plusMinus: 14 },
      { date: "Mar 12", opp: "ORL", result: "W", pts: 22, reb: 7, ast: 3, plusMinus: 9 },
      { date: "Mar 10", opp: "WAS", result: "W", pts: 28, reb: 5, ast: 5, plusMinus: 20 },
      { date: "Mar 8", opp: "PHI", result: "L", pts: 19, reb: 8, ast: 2, plusMinus: -8 },
      { date: "Mar 6", opp: "CHI", result: "W", pts: 21, reb: 6, ast: 4, plusMinus: 16 },
    ],
    tonightProps: [
      { stat: "Points", line: 22.5, prob: 55, conf: "COND" as const, l5: 23.2, seasonAvg: 23.0, opponentDef: "NYK 11th in wing defense", lean: "OVER" as const },
      { stat: "Rebounds", line: 5.5, prob: 52, conf: "COND" as const, l5: 6.4, seasonAvg: 5.5, opponentDef: "Neutral", lean: "PUSH" as const },
      { stat: "Assists", line: 3.5, prob: 50, conf: "COND" as const, l5: 3.6, seasonAvg: 3.8, opponentDef: "NYK 18th in assist containment", lean: "PUSH" as const },
    ],
  },
  {
    id: "cunnigham",
    name: "Cade Cunningham",
    team: "DET",
    position: "PG",
    number: 2,
    tier: "Franchise" as const,
    ovr: 83,
    identity: "Detroit's future is now — a 6'6\" playmaker who rewrites the point guard definition.",
    stats: { pts: 24.1, reb: 5.7, ast: 8.2, fg_pct: 44.6 },
    attributes: { insideScoring: 80, outsideScoring: 80, playmaking: 88, athleticism: 78, defending: 72, rebounding: 66 },
    dissection: [
      { category: "PLAYMAKING", trait: "Size-creation advantage", detail: "At 6'6\", initiates plays over the top of standard point guard defense. His vision and size create a unique advantage." },
      { category: "OFFENSE", trait: "Mid-range efficiency", detail: "48.6% on pull-up midrange attempts — elite efficiency for a primary ball-handler at his volume." },
      { category: "DEFENSE", trait: "Positional versatility", detail: "Guards 1-through-3 without significant coverage issues. His wingspan and length make him a plus defender." },
      { category: "PLAYMAKING", trait: "Blitz recognition", detail: "When double-teamed, completes skip passes at 62% accuracy — elite for a third-year player." },
    ],
    weaknesses: [
      { trait: "Three-point consistency", detail: "Only 34.2% from three on 5.8 attempts — below average. Teams concede the three and pack the paint." },
      { trait: "Free throw volume", detail: "Only 4.8 attempts per game for a primary ball-handler. Not aggressive enough drawing fouls in the half-court." },
    ],
    scoutQuotes: [
      { quote: "The size and vision combination is the next evolution of the point guard. He's a prototype — we'll be seeing this player type for 20 years.", attribution: "Western Conference scout" },
      { quote: "Detroit is better than their record. Cunningham is better than he's getting credit for. Playoff basketball will show both.", attribution: "Eastern Conference assistant coach" },
    ],
    scoutingReport: "Cade Cunningham is assembling a case as the best point guard in the 2021 draft class — a distinction that includes Jalen Green, Evan Mobley, and Scottie Barnes — through sheer consistency and improvement.\n\nThe 6'6\" frame is his superpower. Traditional point guard defense can't contain him because he sees over every screen and creates pull-up opportunities that simply don't exist for shorter guards.\n\nDetroit's rebuild is further along than the record suggests. Cunningham is the reason. When they add a second star around him, this becomes a team that competes for playoff seeding immediately.",
    tags: ["ASCENDING", "FRANCHISE-CHANGER", "RISING", "SYSTEM"],
    recentGames: [
      { date: "Mar 14", opp: "NYK", result: "L", pts: 26, reb: 6, ast: 10, plusMinus: -8 },
      { date: "Mar 12", opp: "CLE", result: "L", pts: 22, reb: 7, ast: 9, plusMinus: -12 },
      { date: "Mar 10", opp: "PHI", result: "W", pts: 28, reb: 5, ast: 7, plusMinus: 4 },
      { date: "Mar 8", opp: "MIA", result: "W", pts: 24, reb: 8, ast: 11, plusMinus: 9 },
      { date: "Mar 6", opp: "CHI", result: "W", pts: 30, reb: 6, ast: 8, plusMinus: 7 },
    ],
    tonightProps: [],
  },
];

export const MOCK_ANALYSES: Record<string, {
  player: string;
  stat: string;
  threshold: string;
  game: string;
  prob: number;
  lean: "OVER" | "UNDER";
  conf: "HIGH" | "MED" | "COND";
  splits: { label: string; val: string; count: string }[];
  signal: string;
  lastFive: { date: string; opp: string; result: number; hit: boolean }[];
  market: { courtside: number; fanDuel: number; line: string; diverge: boolean; divergeDir: "OVER" | "UNDER" };
  form: string;
  defense: string;
}> = {
  default: {
    player: "Jalen Brunson",
    stat: "Points",
    threshold: "Over 30",
    game: "vs BOS · Home · Tonight 7:30 PM ET",
    prob: 42,
    lean: "UNDER",
    conf: "MED",
    splits: [
      { label: "Season", val: "38%", count: "62 gms" },
      { label: "Last 10", val: "40%", count: "4 of 10" },
      { label: "Last 5", val: "60%", count: "3 of 5" },
      { label: "vs BOS", val: "29%", count: "7 gms" },
      { label: "Home", val: "48%", count: "31 gms" },
    ],
    signal: "Brunson's L5 surge (+2.8 over season avg) meets Boston's top-5 defense (104.1 DRTG). Hot streaks vs elite defense regress historically. Brunson vs BOS: 2-of-7 over 30 points all-time. The Garden crowd helps — but not enough to overcome the matchup math.",
    lastFive: [
      { date: "Mar 14", opp: "MIA", result: 34, hit: true },
      { date: "Mar 12", opp: "CHA", result: 31, hit: true },
      { date: "Mar 10", opp: "DET", result: 27, hit: false },
      { date: "Mar 8", opp: "IND", result: 33, hit: true },
      { date: "Mar 6", opp: "ORL", result: 24, hit: false },
    ],
    market: { courtside: 42, fanDuel: 53.5, line: "O29.5 @ 1.87x", diverge: true, divergeDir: "OVER" },
    form: "HOT",
    defense: "ELITE DEF · BOS 104.1 DRTG",
  },
  sga: {
    player: "Shai Gilgeous-Alexander",
    stat: "Points",
    threshold: "Over 32",
    game: "vs DAL · Home · Tonight",
    prob: 74,
    lean: "OVER",
    conf: "HIGH",
    splits: [
      { label: "Season", val: "62%", count: "64 gms" },
      { label: "Last 10", val: "70%", count: "7 of 10" },
      { label: "Last 5", val: "80%", count: "4 of 5" },
      { label: "vs DAL", val: "78%", count: "9 gms" },
      { label: "Home", val: "68%", count: "32 gms" },
    ],
    signal: "SGA has eviscerated Dallas all season — averaging 36.2 PPG vs DAL across 4 meetings. The Mavs surrender 112.8 points per 100 to guards and their on-ball defense without Doncic is structurally broken. This is a spot play.",
    lastFive: [
      { date: "Mar 14", opp: "DAL", result: 38, hit: true },
      { date: "Mar 12", opp: "DEN", result: 29, hit: false },
      { date: "Mar 10", opp: "MEM", result: 35, hit: true },
      { date: "Mar 8", opp: "LAL", result: 31, hit: false },
      { date: "Mar 6", opp: "POR", result: 26, hit: false },
    ],
    market: { courtside: 74, fanDuel: 68, line: "O31.5 @ 1.91x", diverge: true, divergeDir: "OVER" },
    form: "SCORCHING",
    defense: "WEAK DEF · DAL 112.8 DRTG",
  },
  jokic: {
    player: "Nikola Jokic",
    stat: "Triple-Double",
    threshold: "Yes",
    game: "vs LAL · Home · Tonight",
    prob: 38,
    lean: "UNDER",
    conf: "MED",
    splits: [
      { label: "Season", val: "32%", count: "64 gms" },
      { label: "Last 10", val: "40%", count: "4 of 10" },
      { label: "Last 5", val: "60%", count: "3 of 5" },
      { label: "vs LAL", val: "50%", count: "8 gms" },
      { label: "Home", val: "36%", count: "32 gms" },
    ],
    signal: "Jokic needs 10 assists for the triple-double, and the Lakers deploy zone to limit his facilitating. The past 3 LAL vs DEN meetings: 7, 9, 11 assists for Jokic. The floor is there, the ceiling requires a specific defensive collapse.",
    lastFive: [
      { date: "Mar 14", opp: "LAL", result: 11, hit: true },
      { date: "Mar 12", opp: "POR", result: 8, hit: false },
      { date: "Mar 10", opp: "UTA", result: 12, hit: true },
      { date: "Mar 8", opp: "PHX", result: 7, hit: false },
      { date: "Mar 6", opp: "SAC", result: 9, hit: false },
    ],
    market: { courtside: 38, fanDuel: 45, line: "Yes @ 2.20x", diverge: true, divergeDir: "UNDER" },
    form: "HOT",
    defense: "GOOD DEF · LAL 108.2 DRTG",
  },
};

export const ARENA_ARTICLES = [
  {
    id: "1",
    type: "Preview" as const,
    headline: "Celtics at Knicks: The Garden Needs This One",
    excerpt: "Boston enters Madison Square Garden with the best record in the East but facing a Knicks team that hasn't lost a home game in 12 days. Brunson vs. the Boston defense is the matchup of the week.",
    date: "Mar 15, 2026",
    readTime: "6 min read",
    featured: true,
    author: "Courtside Analytics",
  },
  {
    id: "2",
    type: "Verdict" as const,
    headline: "OKC's Demolition of Dallas Completes the Big Three Era Postmortem",
    excerpt: "SGA dropped 38 on a Mavs defense without Doncic, Kyrie, or meaningful resistance. The Thunder are not just the best team in the West — they may be the best team in a generation.",
    date: "Mar 14, 2026",
    readTime: "8 min read",
    featured: false,
    author: "Courtside Analytics",
  },
  {
    id: "3",
    type: "Spotlight" as const,
    headline: "The Maxey Revelation: What Philadelphia's Guard Proves Without Embiid",
    excerpt: "Tyrese Maxey's 34-point performance against Miami wasn't an aberration. It was the latest data point in an argument that has been building all season: Philly doesn't need Embiid to compete.",
    date: "Mar 14, 2026",
    readTime: "10 min read",
    featured: false,
    author: "Courtside Analytics",
  },
  {
    id: "4",
    type: "Rankings" as const,
    headline: "Power Rankings: Week 20 — Denver's Rise Changes the Calculus",
    excerpt: "The Nuggets have won 14 of their last 16 with Jokic averaging a 28/13/10 clip. OKC remains at #1, but this week's numbers force a serious conversation about the West's true hierarchy.",
    date: "Mar 13, 2026",
    readTime: "12 min read",
    featured: false,
    author: "Courtside Analytics",
  },
  {
    id: "5",
    type: "Preview" as const,
    headline: "Golden State at Memphis: The Curry Comeback Tour Hits Tennessee",
    excerpt: "Stephen Curry returns from a 6-game ankle absence and immediately faces a Memphis team playing desperate basketball. Everything you need to know about tonight's 10 PM tipoff.",
    date: "Mar 15, 2026",
    readTime: "5 min read",
    featured: false,
    author: "Courtside Analytics",
  },
  {
    id: "6",
    type: "Spotlight" as const,
    headline: "Jokic's Triple-Double Pace Would Be Historic. Here's What the Numbers Actually Say.",
    excerpt: "Nikola Jokic is on pace for 27 triple-doubles this season. Oscar Robertson's single-season record of 41 is safe — but the efficiency at which Jokic produces them has no historical comparison.",
    date: "Mar 12, 2026",
    readTime: "9 min read",
    featured: false,
    author: "Courtside Analytics",
  },
];

export const TRENDING_INSIGHTS = [
  { text: "Jokic has recorded a triple-double in 4 of his last 5 games", query: "Jokic triple-double tonight?" },
  { text: "Brunson averaging 31.2 pts over last 5 (season avg: 28.4)", query: "Will Brunson score 30+ tonight?" },
  { text: "OKC is 12-1 at home when SGA scores 30+", query: "SGA over 30 points vs Dallas?" },
];
