/**
 * Edge Protocol — Conversational Game Analysis Engine
 *
 * Takes a natural language query ("who wins MIA vs PHI tonight?"),
 * orchestrates multiple Edge prices, enriches with contextual factors,
 * and returns a Claude-generated narrative analysis with betting angles.
 *
 * Designed for Polymarket/Kalshi users who want informed prediction
 * market positions backed by statistical analysis.
 *
 * Usage:
 *   const { analyzeQuery } = require('./analyze');
 *   const result = await analyzeQuery("who wins MIA vs PHI tonight?");
 */

'use strict';

const https = require('https');
const { pricebet } = require('./odds-agent');
const { buildContext, formatContextForPrompt } = require('./context');
const { calcProbability } = require('./calc');
const { getRivalryIntensity } = require('./factors/rivalry-intensity');
const { getCoachingProfile } = require('./factors/coaching-profiles');

function normaliseTeam(name) {
  return (name || '').toLowerCase().replace(/[^a-z0-9 ]/g, '').trim();
}

// ── Config ──────────────────────────────────────────────────────────────────

const ANALYSIS_MODEL = 'claude-4-sonnet-20250514';
const PARSE_MODEL = 'claude-haiku-4-5-20251001';

// Top players per team for prop analysis (fallback if no summaries)
const STAR_PLAYERS = {
  ATL: ['Trae Young', 'Dejounte Murray'], BOS: ['Jayson Tatum', 'Jaylen Brown', 'Nikola Vucevic'],
  BKN: ['Cameron Johnson', 'Dennis Schroder'], CHA: ['LaMelo Ball', 'Brandon Miller'],
  CHI: ['Coby White', 'Nikola Vucevic'], CLE: ['Donovan Mitchell', 'Darius Garland', 'Evan Mobley'],
  DAL: ['Kyrie Irving', 'PJ Washington'], DEN: ['Nikola Jokic', 'Jamal Murray', 'Michael Porter Jr.'],
  DET: ['Cade Cunningham', 'Jaden Ivey'], GSW: ['Stephen Curry', 'Andrew Wiggins', 'Draymond Green'],
  HOU: ['Kevin Durant', 'Alperen Sengun', 'Jalen Green'], IND: ['Tyrese Haliburton', 'Pascal Siakam'],
  LAC: ['James Harden', 'Norman Powell'], LAL: ['LeBron James', 'Luka Doncic', 'Anthony Davis'],
  MEM: ['Ja Morant', 'Jaren Jackson Jr.', 'Desmond Bane'], MIA: ['Jimmy Butler', 'Bam Adebayo', 'Tyler Herro'],
  MIL: ['Giannis Antetokounmpo', 'Damian Lillard', 'Khris Middleton'], MIN: ['Anthony Edwards', 'Julius Randle', 'Rudy Gobert'],
  NOP: ['Zion Williamson', 'Brandon Ingram', 'CJ McCollum'], NYK: ['Jalen Brunson', 'Karl-Anthony Towns', 'OG Anunoby'],
  OKC: ['Shai Gilgeous-Alexander', 'Jalen Williams', 'Chet Holmgren'], ORL: ['Paolo Banchero', 'Franz Wagner'],
  PHI: ['Paul George', 'Tyrese Maxey'], PHX: ['Devin Booker', 'Bradley Beal'],
  POR: ['Jrue Holiday', 'Anfernee Simons', 'Scoot Henderson'], SAC: ['De\'Aaron Fox', 'Zach LaVine', 'Domantas Sabonis'],
  SAS: ['Victor Wembanyama', 'Devin Vassell'], TOR: ['Scottie Barnes', 'RJ Barrett'],
  UTA: ['Lauri Markkanen', 'Collin Sexton'], WAS: ['Jordan Poole', 'Kyle Kuzma'],
};

// ── Disclaimer (appended to ALL responses) ──────────────────────────────────

const DISCLAIMER = '\n\n---\n_This analysis is generated by Edge for educational and informational purposes only. It does not constitute financial advice. Always do your own research before making any decisions._';

// ── Shared system prompt ────────────────────────────────────────────────────

const ANALYSIS_SYSTEM_PROMPT = `You are Edge — an NBA intelligence engine that combines statistical modeling (77K+ game logs), real-time sportsbook odds calibration, coaching analysis, and contextual factors to produce data-driven NBA analysis.

Your analysis should be:
- OBJECTIVE — present probabilities, statistical edges, and reasoning. Never tell users what to do with their money. Say "Team X has a 62% probability based on..." not "Bet on Team X."
- Data-driven — cite specific numbers, splits, trends, and the statistical basis for your conclusions
- Balanced — present both sides. Acknowledge uncertainty and key risks
- Structured — use the section format provided

CRITICAL RULES:
- Never use directive language like "bet on", "hammer", "smash", "fade", "take". Instead use objective framing: "has higher probability", "shows statistical edge", "the data suggests"
- Always present both outcomes with their respective probabilities
- When discussing prediction markets, frame as "this probability implies X position would have positive expected value" not "buy/sell X"
- Flag uncertainty prominently — models can be wrong

Format your response with these sections:
🏀 VERDICT (2-3 sentences on the most likely outcome and why)
📊 BY THE NUMBERS (key stats and splits that drive the analysis)
🔍 MARKET ANGLES (2-3 observations on where Edge probabilities differ from market consensus, framed objectively)
⚠️ KEY RISKS (factors that could change the outcome)
💡 CONFIDENCE LEVEL (how much data supports this analysis — high/medium/low with explanation)`;

// ── General NBA analysis (no specific matchup required) ─────────────────────

async function analyzeGeneral(query, teams, gameDate, detail, reasoning, startTime) {
  // Build context from whatever teams/data we have
  const contextParts = [];

  // If 1 team found, load its context
  if (teams.length === 1) {
    reasoning.push(`Single team detected: ${teams[0]}`);
    try {
      const stars = (STAR_PLAYERS[teams[0]] || []).slice(0, 3);
      const ctx = await buildContext(stars[0] || teams[0], 'points', '', gameDate, { team: teams[0] });
      if (ctx) contextParts.push(formatContextForPrompt(ctx));
      const coach = getCoachingProfile(teams[0]);
      if (coach) contextParts.push(`${teams[0]} COACH: ${coach.coach} (pace: ${coach.pace}, defense: ${coach.defensiveScheme}, clutch: ${coach.clutchRating})`);
    } catch (e) {
      reasoning.push(`Context error: ${e.message}`);
    }
  }

  // Load coaching profiles for all mentioned teams or top contenders for general questions
  const topContenders = ['BOS', 'OKC', 'CLE', 'DEN', 'NYK', 'MIL', 'LAL', 'HOU', 'MIN', 'PHX'];
  const relevantTeams = teams.length > 0 ? teams : topContenders;
  const coachingSummary = relevantTeams.map(t => {
    const c = getCoachingProfile(t);
    return c ? `${t}: ${c.coach} (pace: ${c.pace}, clutch: ${c.clutchRating})` : null;
  }).filter(Boolean).join('\n');

  // Get today's games for context
  let todayGames = '';
  try {
    const https = require('https');
    const raw = await new Promise((resolve, reject) => {
      https.get('https://cdn.nba.com/static/json/liveData/scoreboard/todaysScoreboard_00.json',
        { headers: { 'User-Agent': 'Mozilla/5.0' }, timeout: 5000 },
        res => { let d = ''; res.on('data', c => d += c); res.on('end', () => resolve(d)); }
      ).on('error', reject);
    });
    const sb = JSON.parse(raw);
    todayGames = (sb.scoreboard?.games || []).map(g =>
      `${g.awayTeam.teamTricode} @ ${g.homeTeam.teamTricode} (${g.gameStatusText})`
    ).join(', ');
  } catch { /* ignore */ }

  // Load playoff urgency for top contenders if general question
  let standingsContext = '';
  if (teams.length === 0) {
    try {
      const { getPlayoffUrgency } = require('./factors/playoff-urgency');
      const urgencies = await Promise.all(topContenders.slice(0, 6).map(async t => {
        const u = await getPlayoffUrgency(t, gameDate);
        return u ? `${t}: ${u.tier} (${(u.urgency * 100).toFixed(0)}%) — ${u.reason}` : null;
      }));
      standingsContext = urgencies.filter(Boolean).join('\n');
    } catch { /* ignore */ }
  }

  const userPrompt = `User query: "${query}"

${todayGames ? `TODAY'S GAMES: ${todayGames}` : ''}

${contextParts.length > 0 ? 'TEAM CONTEXT:\n' + contextParts.join('\n\n') : ''}

${coachingSummary ? 'COACHING PROFILES:\n' + coachingSummary : ''}

${standingsContext ? 'PLAYOFF STANDINGS/URGENCY:\n' + standingsContext : ''}

Date: ${gameDate}

Provide a thorough, objective, data-driven analysis responding to the user's question. Use the NBA data above where relevant.${detail === 'brief' ? ' Keep it concise — 250 words max.' : ''}`;

  let analysis = '';
  try {
    analysis = await callClaude(ANALYSIS_MODEL, ANALYSIS_SYSTEM_PROMPT, userPrompt, detail === 'brief' ? 800 : 2000);
    reasoning.push(`General analysis generated via ${ANALYSIS_MODEL}`);
  } catch (e) {
    reasoning.push(`Analysis failed: ${e.message}`);
    analysis = 'Unable to generate analysis — please try again.';
  }

  if (!analysis) analysis = 'Unable to generate analysis — please try again.';

  // Append disclaimer
  analysis += DISCLAIMER;

  return {
    analysis,
    prices: [],
    context: {
      teams,
      date: gameDate,
      type: teams.length === 1 ? 'team_analysis' : 'general_nba',
    },
    reasoning,
    meta: {
      query,
      teams,
      date: gameDate,
      prices_count: 0,
      duration_ms: Date.now() - startTime,
      model: ANALYSIS_MODEL,
      type: teams.length === 1 ? 'team_analysis' : 'general_nba',
    },
  };
}

// All NBA team abbreviations with common name variants
const TEAM_NAMES = {
  'heat': 'MIA', 'miami': 'MIA', 'mia': 'MIA',
  '76ers': 'PHI', 'sixers': 'PHI', 'philadelphia': 'PHI', 'philly': 'PHI', 'phi': 'PHI',
  'celtics': 'BOS', 'boston': 'BOS', 'bos': 'BOS',
  'knicks': 'NYK', 'new york': 'NYK', 'nyk': 'NYK',
  'lakers': 'LAL', 'la lakers': 'LAL', 'los angeles lakers': 'LAL', 'lal': 'LAL',
  'warriors': 'GSW', 'golden state': 'GSW', 'gsw': 'GSW',
  'nuggets': 'DEN', 'denver': 'DEN', 'den': 'DEN',
  'bucks': 'MIL', 'milwaukee': 'MIL', 'mil': 'MIL',
  'cavaliers': 'CLE', 'cavs': 'CLE', 'cleveland': 'CLE', 'cle': 'CLE',
  'thunder': 'OKC', 'oklahoma': 'OKC', 'okc': 'OKC',
  'suns': 'PHX', 'phoenix': 'PHX', 'phx': 'PHX',
  'timberwolves': 'MIN', 'wolves': 'MIN', 'minnesota': 'MIN', 'min': 'MIN',
  'grizzlies': 'MEM', 'memphis': 'MEM', 'mem': 'MEM',
  'hawks': 'ATL', 'atlanta': 'ATL', 'atl': 'ATL',
  'nets': 'BKN', 'brooklyn': 'BKN', 'bkn': 'BKN',
  'hornets': 'CHA', 'charlotte': 'CHA', 'cha': 'CHA',
  'bulls': 'CHI', 'chicago': 'CHI', 'chi': 'CHI',
  'mavericks': 'DAL', 'mavs': 'DAL', 'dallas': 'DAL', 'dal': 'DAL',
  'pistons': 'DET', 'detroit': 'DET', 'det': 'DET',
  'rockets': 'HOU', 'houston': 'HOU', 'hou': 'HOU',
  'pacers': 'IND', 'indiana': 'IND', 'ind': 'IND',
  'clippers': 'LAC', 'la clippers': 'LAC', 'lac': 'LAC',
  'pelicans': 'NOP', 'new orleans': 'NOP', 'nop': 'NOP',
  'magic': 'ORL', 'orlando': 'ORL', 'orl': 'ORL',
  'trail blazers': 'POR', 'blazers': 'POR', 'portland': 'POR', 'por': 'POR',
  'kings': 'SAC', 'sacramento': 'SAC', 'sac': 'SAC',
  'spurs': 'SAS', 'san antonio': 'SAS', 'sas': 'SAS',
  'raptors': 'TOR', 'toronto': 'TOR', 'tor': 'TOR',
  'jazz': 'UTA', 'utah': 'UTA', 'uta': 'UTA',
  'wizards': 'WAS', 'washington': 'WAS', 'was': 'WAS',
};

// ── Helpers ─────────────────────────────────────────────────────────────────

function callClaude(model, system, user, maxTokens = 1500) {
  const apiKey = (process.env.ANTHROPIC_API_KEY || '').trim();
  if (!apiKey) return Promise.resolve(null);

  const body = JSON.stringify({
    model,
    max_tokens: maxTokens,
    system,
    messages: [{ role: 'user', content: user }],
  });

  return new Promise((resolve, reject) => {
    const req = https.request({
      hostname: 'api.anthropic.com',
      path: '/v1/messages',
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'anthropic-version': '2023-06-01',
        'x-api-key': apiKey,
        'Content-Length': Buffer.byteLength(body),
      },
    }, (res) => {
      let d = '';
      res.on('data', c => d += c);
      res.on('end', () => {
        try {
          const parsed = JSON.parse(d);
          resolve(parsed.content?.[0]?.text || null);
        } catch { resolve(null); }
      });
    });
    req.on('error', reject);
    req.write(body);
    req.end();
  });
}

function extractTeams(query) {
  const lower = query.toLowerCase();
  const found = [];
  // Sort by key length descending to match longer names first ("la lakers" before "la")
  const sorted = Object.entries(TEAM_NAMES).sort((a, b) => b[0].length - a[0].length);
  for (const [name, abbr] of sorted) {
    if (lower.includes(name) && !found.includes(abbr)) {
      found.push(abbr);
    }
  }
  return found.slice(0, 2);
}

function resolveDate(query) {
  const lower = query.toLowerCase();
  const today = new Date();
  if (lower.includes('tonight') || lower.includes('today')) {
    return today.toISOString().slice(0, 10);
  }
  if (lower.includes('tomorrow')) {
    const d = new Date(today);
    d.setDate(d.getDate() + 1);
    return d.toISOString().slice(0, 10);
  }
  // Try to extract YYYY-MM-DD
  const dateMatch = query.match(/(\d{4}-\d{2}-\d{2})/);
  if (dateMatch) return dateMatch[1];
  // Default to today
  return today.toISOString().slice(0, 10);
}

// ── Main Analysis Pipeline ──────────────────────────────────────────────────

/**
 * Analyze a natural language NBA query.
 *
 * @param {string} query - Natural language question
 * @param {object} opts - { detail: 'brief'|'full' }
 * @returns {object} { analysis, prices, context, reasoning, meta }
 */
async function analyzeQuery(query, opts = {}) {
  const startTime = Date.now();
  const detail = opts.detail || 'full';
  const reasoning = [];

  // ── Step 1: Parse query ─────────────────────────────────────────────────
  const teams = extractTeams(query);
  const gameDate = resolveDate(query);

  if (teams.length < 2) {
    // Try Claude for more complex parsing
    try {
      const parseResult = await callClaude(PARSE_MODEL,
        'Extract NBA team abbreviations from the query. Return ONLY a JSON object: {"teams":["XXX","YYY"],"players":["Name"],"stat":"points|rebounds|assists|null","date":"YYYY-MM-DD"}. Use standard 3-letter NBA abbreviations.',
        query, 200
      );
      if (parseResult) {
        const parsed = JSON.parse(parseResult);
        if (parsed.teams?.length >= 2) {
          teams.length = 0;
          teams.push(...parsed.teams.map(t => t.toUpperCase()).slice(0, 2));
        }
      }
    } catch { /* use what we have */ }
  }

  // ── Route by query type ──────────────────────────────────────────────────
  // 2 teams → head-to-head matchup analysis
  // 1 team or player mention → team/player-focused analysis
  // 0 teams → general NBA intelligence question

  if (teams.length < 2) {
    // General or single-team NBA question — use Claude with full context
    return await analyzeGeneral(query, teams, gameDate, detail, reasoning, startTime);
  }

  reasoning.push(`Parsed: ${teams[0]} vs ${teams[1]} on ${gameDate}`);

  // ── Step 2: Run prices ──────────────────────────────────────────────────
  const prices = [];

  // Game winner — use market h2h odds directly via getMarketComp
  const { getMarketComp } = require('./market');
  let winProbA = null, winProbB = null;
  try {
    const marketA = await getMarketComp(teams[0], 'game_win', 'over', 0.5, teams[1], gameDate);
    if (marketA.found) {
      // h2h market returns both sides — find each team
      const homeTeam = marketA.raw?.home_team || '';
      const awayTeam = marketA.raw?.away_team || '';

      // The implied_prob from getMarketComp is for the first outcome
      // We need to get both sides from the raw event
      winProbA = marketA.implied_prob;
      winProbB = winProbA ? (1 - winProbA) : null;

      // Determine which probability belongs to which team
      const normA = normaliseTeam(teams[0]);
      const isAHome = normaliseTeam(homeTeam).includes(normA) || normA.includes(normaliseTeam(homeTeam));
      const matchedLine = normaliseTeam(marketA.line || '');
      const lineMatchesA = matchedLine.includes(normA) || normA.includes(matchedLine);

      if (!lineMatchesA) {
        // The market line was for team B, swap
        [winProbA, winProbB] = [winProbB, winProbA];
      }

      if (winProbA !== null) {
        prices.push({
          type: 'game_win', team: teams[0],
          probability: winProbA, decimal_odds: winProbA > 0 ? Math.round(100 / winProbA) / 100 : null,
          american: winProbA >= 0.5 ? '-' + Math.round(winProbA / (1 - winProbA) * 100) : '+' + Math.round((1 - winProbA) / winProbA * 100),
          has_market_comp: true, market_reference: marketA.market_reference,
          confidence_tier: 'high', source: 'market_h2h',
        });
      }
      if (winProbB !== null) {
        prices.push({
          type: 'game_win', team: teams[1],
          probability: winProbB, decimal_odds: winProbB > 0 ? Math.round(100 / winProbB) / 100 : null,
          american: winProbB >= 0.5 ? '-' + Math.round(winProbB / (1 - winProbB) * 100) : '+' + Math.round((1 - winProbB) / winProbB * 100),
          has_market_comp: true, market_reference: marketA.market_reference,
          confidence_tier: 'high', source: 'market_h2h',
        });
      }
    }
  } catch (e) {
    reasoning.push(`Game winner market fetch failed: ${e.message}`);
  }

  reasoning.push(`Game winner: ${teams[0]}=${winProbA !== null ? (winProbA * 100).toFixed(1) + '%' : 'N/A'}, ${teams[1]}=${winProbB !== null ? (winProbB * 100).toFixed(1) + '%' : 'N/A'}`);

  // Key player props (top 2-3 per team, points only for speed)
  const starA = (STAR_PLAYERS[teams[0]] || []).slice(0, 3);
  const starB = (STAR_PLAYERS[teams[1]] || []).slice(0, 3);
  const allStars = [
    ...starA.map(p => ({ player: p, team: teams[0], opponent: teams[1] })),
    ...starB.map(p => ({ player: p, team: teams[1], opponent: teams[0] })),
  ];

  // Run player prop prices in parallel (batches of 4 to avoid overloading)
  for (let i = 0; i < allStars.length; i += 4) {
    const batch = allStars.slice(i, i + 4);
    const results = await Promise.all(batch.map(async ({ player, team, opponent }) => {
      // Get player's average to set a reasonable threshold
      const stats = calcProbability(player, 'points', 'over', 20);
      const avg = stats.mean || stats.context?.avg || 20;
      const threshold = Math.round(avg - 0.5); // just under average for a meaningful line

      const result = await pricebet(player, 'points', 'over', threshold, {
        opponent, game_date: gameDate, player_team: team,
      });
      return { player, team, opponent, threshold, result };
    }));

    for (const { player, team, threshold, result } of results) {
      if (!result.error) {
        prices.push({
          type: 'player_prop',
          player,
          team,
          stat: 'points',
          threshold,
          probability: result.probability,
          decimal_odds: result.decimal_odds,
          american: result.american,
          has_market_comp: result.has_market_comp,
          market_reference: result.market_reference,
          confidence_tier: result.confidence_tier,
          recent_5: result.recent_5,
          mean: result.mean || result.context?.avg,
        });
      }
    }
  }

  reasoning.push(`Priced ${prices.filter(p => p.type === 'player_prop').length} player props`);

  // ── Step 3: Gather context ──────────────────────────────────────────────
  let contextA = null, contextB = null;
  try {
    [contextA, contextB] = await Promise.all([
      buildContext(starA[0] || teams[0], 'points', teams[1], gameDate, { team: teams[0] }),
      buildContext(starB[0] || teams[1], 'points', teams[0], gameDate, { team: teams[1] }),
    ]);
  } catch (e) {
    reasoning.push(`Context error: ${e.message}`);
  }

  const rivalry = getRivalryIntensity(teams[0], teams[1]);
  const coachA = getCoachingProfile(teams[0]);
  const coachB = getCoachingProfile(teams[1]);

  // ── Step 4: Generate analysis via Claude Sonnet ─────────────────────────
  const priceSummary = prices.map(p => {
    if (p.type === 'game_win') {
      return `GAME WINNER: ${p.team} — ${(p.probability * 100).toFixed(1)}% probability, odds ${p.decimal_odds}x (${p.american})${p.has_market_comp ? ', market: ' + JSON.stringify(p.market_reference) : ''}`;
    }
    return `PLAYER PROP: ${p.player} (${p.team}) over ${p.threshold} pts — ${(p.probability * 100).toFixed(1)}% probability, mean=${p.mean?.toFixed?.(1) || '?'}, recent 5: [${(p.recent_5 || []).join(', ')}], confidence=${p.confidence_tier}${p.has_market_comp ? ', market: ' + JSON.stringify(p.market_reference) : ''}`;
  }).join('\n');

  const contextSummary = [
    contextA ? formatContextForPrompt(contextA) : '',
    contextB ? formatContextForPrompt(contextB) : '',
    rivalry.intensity > 0.4 ? `RIVALRY: ${rivalry.intensity.toFixed(2)} intensity — ${rivalry.notes}` : '',
    coachA ? `${teams[0]} COACH: ${coachA.coach} (pace: ${coachA.pace}, defense: ${coachA.defensiveScheme}, clutch: ${coachA.clutchRating})` : '',
    coachB ? `${teams[1]} COACH: ${coachB.coach} (pace: ${coachB.pace}, defense: ${coachB.defensiveScheme}, clutch: ${coachB.clutchRating})` : '',
  ].filter(Boolean).join('\n\n');

  const systemPrompt = ANALYSIS_SYSTEM_PROMPT;

  const userPrompt = `User query: "${query}"

EDGE PRICING DATA:
${priceSummary}

CONTEXTUAL INTELLIGENCE:
${contextSummary}

Game date: ${gameDate}
${teams[0]} vs ${teams[1]}

Generate a sharp, data-driven analysis for a prediction market trader.${detail === 'brief' ? ' Keep it concise — 200 words max.' : ''}`;

  let analysis = '';
  try {
    analysis = await callClaude(ANALYSIS_MODEL, systemPrompt, userPrompt, detail === 'brief' ? 800 : 2000);
    reasoning.push(`Analysis generated via ${ANALYSIS_MODEL} (${detail} mode)`);
  } catch (e) {
    reasoning.push(`Analysis generation failed: ${e.message}`);
    analysis = `Edge priced ${teams[0]} at ${winProbA !== null ? (winProbA * 100).toFixed(1) + '%' : 'N/A'} and ${teams[1]} at ${winProbB !== null ? (winProbB * 100).toFixed(1) + '%' : 'N/A'}. Full analysis unavailable — Claude API error.`;
  }

  if (!analysis) {
    analysis = `Edge priced ${teams[0]} at ${winProbA !== null ? (winProbA * 100).toFixed(1) + '%' : 'N/A'} and ${teams[1]} at ${winProbB !== null ? (winProbB * 100).toFixed(1) + '%' : 'N/A'}. Full analysis unavailable.`;
  }

  // Append disclaimer to all responses
  analysis += DISCLAIMER;

  return {
    analysis,
    prices: prices.map(p => ({
      type: p.type,
      team: p.team,
      player: p.player || null,
      stat: p.stat || 'game_win',
      threshold: p.threshold,
      probability: p.probability,
      decimal_odds: p.decimal_odds,
      american: p.american,
      confidence_tier: p.confidence_tier,
      has_market_comp: p.has_market_comp,
      market_reference: p.market_reference,
    })),
    context: {
      teams,
      date: gameDate,
      rivalry,
      coaching: { [teams[0]]: coachA, [teams[1]]: coachB },
    },
    reasoning,
    meta: {
      query,
      teams,
      date: gameDate,
      prices_count: prices.length,
      duration_ms: Date.now() - startTime,
      model: ANALYSIS_MODEL,
    },
  };
}

module.exports = { analyzeQuery };
